CREATE OR REPLACE PROCEDURE PROC_EndsData_Check(p_VERSION IN varchar2,p_REPORTINST IN varchar2,p_ENDDATE IN varchar2,FIRSTRESULT IN VARCHAR2,PAGECOUNT IN VARCHAR2,rt OUT sys_refcursor)
AS

BEGIN

IF p_VERSION = '2.1'
THEN 

OPEN rt FOR
WITH CTE_JKRXX
AS (
SELECT DKKBM,CASE WHEN JKRZWMC IS NULL OR JKRZWMC = '' THEN JKRWWMC ELSE JKRZWMC END AS CTE_JKRMC,ZZJGDM,MAX(QY_JKRGKXX.EXTEND2) AS EXTEND2 FROM QY_JKRGKXX,QY_JKRGK_JC,REPORTINSTSUBINFO WHERE QY_JKRGKXX.FOREIGNID = QY_JKRGK_JC.AUTOID AND INSTINFO = STRINSTCODE AND QY_JKRGKXX.EXTEND2 <= p_ENDDATE AND strReportInstCode = p_REPORTINST AND XXJLCZLX = '1' AND QY_JKRGKXX.RPTFEEDBACKTYPE = '2' GROUP BY FOREIGNID,DKKBM,JKRZWMC,JKRWWMC,ZZJGDM
)
SELECT DKKBM,ZZJGDM,JKRMC,CASE WHEN DKHTBS = 0 AND JJBS = 0 THEN NULL ELSE DKHTBS END AS DKHTBS,CASE WHEN DKHTBS = 0 AND JJBS = 0 THEN NULL ELSE DKFSE END AS DKFSE,CASE WHEN DKHTBS = 0 AND JJBS = 0 THEN NULL ELSE DKYE END AS DKYE,CASE WHEN DKHTBS = 0 AND JJBS = 0 THEN NULL ELSE JJBS END AS JJBS,CASE WHEN BLBS = 0 THEN NULL ELSE BLBS END AS BLBS,CASE WHEN BLBS = 0 THEN NULL ELSE BLFSE END AS BLFSE,CASE WHEN BLBS = 0 THEN NULL ELSE BLYE END AS BLYE,CASE WHEN PJTXBS = 0 THEN NULL ELSE PJTXBS END AS PJTXBS,CASE WHEN PJTXBS = 0 THEN NULL ELSE PJTXFSE END AS PJTXFSE,CASE WHEN PJTXYE = 0 THEN NULL ELSE PJTXYE END AS PJTXYE,CASE WHEN MYRZXYBS = 0 AND MYRZYWBS = 0 THEN NULL ELSE MYRZXYBS END AS MYRZXYBS,CASE WHEN MYRZXYBS = 0 AND MYRZYWBS = 0 THEN NULL ELSE MYRZFSE END AS MYRZFSE,CASE WHEN MYRZXYBS = 0 AND MYRZYWBS = 0 THEN NULL ELSE MYRZYE END AS MYRZYE,CASE WHEN MYRZXYBS = 0 AND MYRZYWBS = 0 THEN NULL ELSE MYRZYWBS END AS MYRZYWBS,CASE WHEN XYZBS = 0 THEN NULL ELSE XYZBS END AS XYZBS,CASE WHEN XYZBS = 0 THEN NULL ELSE XYZFSE END AS XYZFSE,CASE WHEN XYZBS = 0 THEN NULL ELSE XYZYE END AS XYZYE,CASE WHEN BHBS = 0 THEN NULL ELSE BHBS END AS BHBS,CASE WHEN BHBS = 0 THEN NULL ELSE BHFSE END AS BHFSE,CASE WHEN BHBS = 0 THEN NULL ELSE BHYE END AS BHYE,CASE WHEN CDHPBS = 0 THEN NULL ELSE CDHPBS END AS CDHPBS,CASE WHEN CDHPBS = 0 THEN NULL ELSE CDHPFSE END AS CDHPFSE,CASE WHEN CDHPBS = 0 THEN NULL ELSE CDHPYE END AS CDHPYE,CASE WHEN GKSXBS = 0 THEN NULL ELSE GKSXBS END AS GKSXBS,CASE WHEN GKSXBS = 0 THEN NULL ELSE GKSXFSE END AS GKSXFSE,CASE WHEN BZHTBS = 0 THEN NULL ELSE BZHTBS END AS BZHTBS,CASE WHEN BZHTBS = 0 THEN NULL ELSE BZFSE END AS BZFSE,CASE WHEN BZHTBS = 0 THEN NULL ELSE BZYE END AS BZYE,CASE WHEN DYHTBS = 0 THEN NULL ELSE DYHTBS END AS DYHTBS,CASE WHEN DYHTBS = 0 THEN NULL ELSE DYFSE END AS DYFSE,CASE WHEN DYHTBS = 0 THEN NULL ELSE DYYE END AS DYYE,CASE WHEN ZYHTBS = 0 THEN NULL ELSE ZYHTBS END AS ZYHTBS,CASE WHEN ZYHTBS = 0 THEN NULL ELSE ZYFSE END AS ZYFSE,CASE WHEN ZYHTBS = 0 THEN NULL ELSE ZYYE END AS ZYYE,CASE WHEN DIANKUANBS = 0 THEN NULL ELSE DIANKUANBS END AS DIANKUANBS,CASE WHEN DIANKUANBS = 0 THEN NULL ELSE DIANKUANFSE END AS DIANKUANFSE,CASE WHEN DIANKUANBS = 0 THEN NULL ELSE DIANKUANYE END AS DIANKUANYE,CASE WHEN BNQXYE = 0 THEN NULL ELSE BNQXYE END AS BNQXYE,CASE WHEN BWQXYE = 0 THEN NULL ELSE BWQXYE END AS BWQXYE,DJJGDM,SUBSTR(SJJZRQ,1,4)||'-'||SUBSTR(SJJZRQ,5,2)||'-'||SUBSTR(SJJZRQ,7,2) AS SJJZRQ FROM (
SELECT DKKBM,ZZJGDM,'"'||MAX(JKRMC)||'"' AS JKRMC,SUM(DKHTBS) AS DKHTBS,SUM(DKFSE) AS DKFSE,SUM(DKYE) AS DKYE,SUM(JJBS) AS JJBS,SUM(BLBS) AS BLBS,SUM(BLFSE) AS BLFSE,SUM(BLYE) AS BLYE,SUM(PJTXBS) AS PJTXBS,SUM(PJTXFSE) AS PJTXFSE,SUM(PJTXYE) AS PJTXYE,SUM(MYRZXYBS) AS MYRZXYBS,SUM(MYRZFSE) AS MYRZFSE,SUM(MYRZYE) AS MYRZYE,SUM(MYRZYWBS) AS MYRZYWBS,SUM(XYZBS) AS XYZBS,SUM(XYZFSE) AS XYZFSE,SUM(XYZYE) AS XYZYE,SUM(BHBS) AS BHBS,SUM(BHFSE) AS BHFSE,SUM(BHYE) AS BHYE,SUM(CDHPBS) AS CDHPBS,SUM(CDHPFSE) AS CDHPFSE,SUM(CDHPYE) AS CDHPYE,SUM(GKSXBS) AS GKSXBS,SUM(GKSXFSE) AS GKSXFSE,SUM(BZHTBS) AS BZHTBS,SUM(BZFSE) AS BZFSE,SUM(BZYE) AS BZYE,SUM(DYHTBS) AS DYHTBS,SUM(DYFSE) AS DYFSE,SUM(DYYE) AS DYYE,SUM(ZYHTBS) AS ZYHTBS,SUM(ZYFSE) AS ZYFSE,SUM(ZYYE) AS ZYYE,SUM(DIANKUANBS) AS DIANKUANBS,SUM(DIANKUANFSE) AS DIANKUANFSE,SUM(DIANKUANYE) AS DIANKUANYE,SUM(BNQXYE) AS BNQXYE,SUM(BWQXYE) AS BWQXYE,MAX(DJJGDM) AS DJJGDM,MAX(SJJZRQ) AS SJJZRQ FROM (

SELECT A.DKKBM,ZZJGDM,CTE_JKRMC AS JKRMC,DKHTBS,0.00 AS DKFSE,0.00 AS DKYE,0 AS JJBS,0 AS BLBS,0.00 AS BLFSE,0.00 AS BLYE,0 AS PJTXBS,0.00 AS PJTXFSE,0.00 AS PJTXYE,0 AS MYRZXYBS,0.00 AS MYRZFSE,0.00 AS MYRZYE,0 AS MYRZYWBS,0 AS XYZBS,0.00 AS XYZFSE,0.00 AS XYZYE,0 AS BHBS,0.00 AS BHFSE,0.00 AS BHYE,0 AS CDHPBS,0.00 AS CDHPFSE,0.00 AS CDHPYE,0 AS GKSXBS,0.00 AS GKSXFSE,0 AS BZHTBS,0.00 AS BZFSE,0.00 AS BZYE,0 AS DYHTBS,0.00 AS DYFSE,0.00 AS DYYE,0 AS ZYHTBS,0.00 AS ZYFSE,0.00 AS ZYYE,0 AS DIANKUANBS,0.00 AS DIANKUANFSE,0.00 AS DIANKUANYE,0.00 AS BNQXYE,0.00 AS BWQXYE,p_REPORTINST AS DJJGDM,p_ENDDATE AS SJJZRQ FROM (
SELECT DKKBM,COUNT(1) AS DKHTBS FROM (
SELECT DKKBM,FOREIGNID,MAX(QY_HTXX.EXTEND2) AS EXTEND2 FROM QY_HTXX,QY_DKYW_JC,REPORTINSTSUBINFO WHERE QY_HTXX.FOREIGNID = QY_DKYW_JC.AUTOID AND INSTINFO = STRINSTCODE AND QY_HTXX.EXTEND2 <= p_ENDDATE AND strReportInstCode = p_REPORTINST AND XXJLCZLX = '1' AND QY_HTXX.RPTFEEDBACKTYPE = '2' GROUP BY DKKBM,FOREIGNID) TEMP WHERE NOT EXISTS(
SELECT * FROM QY_HTXX WHERE QY_HTXX.FOREIGNID = TEMP.FOREIGNID AND QY_HTXX.EXTEND2 = TEMP.EXTEND2 AND QY_HTXX.HTYXZT = '2') 
GROUP BY DKKBM) A 
LEFT JOIN CTE_JKRXX ON A.DKKBM = CTE_JKRXX.DKKBM
UNION 

SELECT B.DKKBM,ZZJGDM,CTE_JKRMC AS JKRMC,0 AS DKHTBS,DKFSE,DKYE,JJBS,0 AS BLBS,0.00 AS BLFSE,0.00 AS BLYE,0 AS PJTXBS,0.00 AS PJTXFSE,0.00 AS PJTXYE,0 AS MYRZXYBS,0.00 AS MYRZFSE,0.00 AS MYRZYE,0 AS MYRZYWBS,0 AS XYZBS,0.00 AS XYZFSE,0.00 AS XYZYE,0 AS BHBS,0.00 AS BHFSE,0.00 AS BHYE,0 AS CDHPBS,0.00 AS CDHPFSE,0.00 AS CDHPYE,0 AS GKSXBS,0.00 AS GKSXFSE,0 AS BZHTBS,0.00 AS BZFSE,0.00 AS BZYE,0 AS DYHTBS,0.00 AS DYFSE,0.00 AS DYYE,0 AS ZYHTBS,0.00 AS ZYFSE,0.00 AS ZYYE,0 AS DIANKUANBS,0.00 AS DIANKUANFSE,0.00 AS DIANKUANYE,0.00 AS BNQXYE,0.00 AS BWQXYE,p_REPORTINST AS DJJGDM,p_ENDDATE AS SJJZRQ FROM (
SELECT DKKBM,SUM(CAST(DKJJJE AS DECIMAL(17,2))) AS DKFSE,SUM(CAST(DKJJYE AS DECIMAL(17,2))) AS DKYE,COUNT(1) AS JJBS FROM (
SELECT FOREIGNID,DKJJJE,DKJJYE,JJBH FROM QY_JJXX WHERE EXISTS(
SELECT * FROM (SELECT FOREIGNID,JJBH,MAX(QY_JJXX.EXTEND2) AS EXTEND2 FROM QY_JJXX,QY_DKYW_JC,REPORTINSTSUBINFO WHERE QY_JJXX.FOREIGNID = QY_DKYW_JC.AUTOID AND INSTINFO = STRINSTCODE AND QY_JJXX.EXTEND2 <= p_ENDDATE AND strReportInstCode = p_REPORTINST AND XXJLCZLX = '1' AND QY_JJXX.RPTFEEDBACKTYPE = '2' GROUP BY FOREIGNID,JJBH) TEMP 
WHERE QY_JJXX.FOREIGNID = TEMP.FOREIGNID AND QY_JJXX.JJBH = TEMP.JJBH AND QY_JJXX.EXTEND2 = TEMP.EXTEND2 AND QY_JJXX.DKJJYE <> '0.00')) TEMP2,QY_DKYW_JC WHERE TEMP2.FOREIGNID = QY_DKYW_JC.AUTOID 
GROUP BY DKKBM) B 
LEFT JOIN CTE_JKRXX ON B.DKKBM = CTE_JKRXX.DKKBM
UNION

SELECT C.DKKBM,ZZJGDM,CTE_JKRMC AS JKRMC,0 AS DKHTBS,0.00 AS DKFSE,0.00 AS DKYE,0 AS JJBS,BLBS,BLFSE,BLYE,0 AS PJTXBS,0.00 AS PJTXFSE,0.00 AS PJTXYE,0 AS MYRZXYBS,0.00 AS MYRZFSE,0.00 AS MYRZYE,0 AS MYRZYWBS,0 AS XYZBS,0.00 AS XYZFSE,0.00 AS XYZYE,0 AS BHBS,0.00 AS BHFSE,0.00 AS BHYE,0 AS CDHPBS,0.00 AS CDHPFSE,0.00 AS CDHPYE,0 AS GKSXBS,0.00 AS GKSXFSE,0 AS BZHTBS,0.00 AS BZFSE,0.00 AS BZYE,0 AS DYHTBS,0.00 AS DYFSE,0.00 AS DYYE,0 AS ZYHTBS,0.00 AS ZYFSE,0.00 AS ZYYE,0 AS DIANKUANBS,0.00 AS DIANKUANFSE,0.00 AS DIANKUANYE,0.00 AS BNQXYE,0.00 AS BWQXYE,p_REPORTINST AS DJJGDM,p_ENDDATE AS SJJZRQ FROM (
SELECT DKKBM,COUNT(1) AS BLBS,SUM(CAST(XZJE AS DECIMAL(17,2))) AS BLFSE,SUM(CAST(XZYE AS DECIMAL(17,2))) AS BLYE FROM QY_BLXZXX WHERE EXISTS (
SELECT * FROM (SELECT FOREIGNID,MAX(QY_BLXZXX.EXTEND2) AS EXTEND2 FROM QY_BLXZXX,QY_BLYW_JC,REPORTINSTSUBINFO WHERE QY_BLXZXX.FOREIGNID = QY_BLYW_JC.AUTOID AND INSTINFO = STRINSTCODE AND QY_BLXZXX.EXTEND2 <= p_ENDDATE AND strReportInstCode = p_REPORTINST AND XXJLCZLX = '1' AND QY_BLXZXX.RPTFEEDBACKTYPE = '2' GROUP BY FOREIGNID) TEMP 
WHERE QY_BLXZXX.FOREIGNID = TEMP.FOREIGNID AND QY_BLXZXX.EXTEND2 = TEMP.EXTEND2 AND QY_BLXZXX.XZYE <> '0.00') 
GROUP BY DKKBM) C 
LEFT JOIN CTE_JKRXX ON C.DKKBM = CTE_JKRXX.DKKBM
UNION

SELECT D.DKKBM,ZZJGDM,CTE_JKRMC AS JKRMC,0 AS DKHTBS,0.00 AS DKFSE,0.00 AS DKYE,0 AS JJBS,0 AS BLBS,0.00 AS BLFSE,0.00 AS BLYE,PJTXBS,PJTXFSE,PJTXYE,0 AS MYRZXYBS,0.00 AS MYRZFSE,0.00 AS MYRZYE,0 AS MYRZYWBS,0 AS XYZBS,0.00 AS XYZFSE,0.00 AS XYZYE,0 AS BHBS,0.00 AS BHFSE,0.00 AS BHYE,0 AS CDHPBS,0.00 AS CDHPFSE,0.00 AS CDHPYE,0 AS GKSXBS,0.00 AS GKSXFSE,0 AS BZHTBS,0.00 AS BZFSE,0.00 AS BZYE,0 AS DYHTBS,0.00 AS DYFSE,0.00 AS DYYE,0 AS ZYHTBS,0.00 AS ZYFSE,0.00 AS ZYYE,0 AS DIANKUANBS,0.00 AS DIANKUANFSE,0.00 AS DIANKUANYE,0.00 AS BNQXYE,0.00 AS BWQXYE,p_REPORTINST AS DJJGDM,p_ENDDATE AS SJJZRQ FROM (
SELECT DKKBM,COUNT(1) AS PJTXBS,SUM(CAST(TXJE AS DECIMAL(17,2))) AS PJTXFSE,SUM(CAST(TXJE AS DECIMAL(17,2))) AS PJTXYE FROM QY_TXYWXX WHERE EXISTS (
SELECT * FROM (SELECT FOREIGNID,MAX(QY_TXYWXX.EXTEND2) AS EXTEND2 FROM QY_TXYWXX,QY_PJTX_JC,REPORTINSTSUBINFO WHERE QY_TXYWXX.FOREIGNID = QY_PJTX_JC.AUTOID AND INSTINFO = STRINSTCODE AND QY_TXYWXX.EXTEND2 <= p_ENDDATE AND strReportInstCode = p_REPORTINST AND XXJLCZLX = '1' AND QY_TXYWXX.RPTFEEDBACKTYPE = '2' GROUP BY FOREIGNID) TEMP 
WHERE QY_TXYWXX.FOREIGNID = TEMP.FOREIGNID AND QY_TXYWXX.EXTEND2 = TEMP.EXTEND2 AND QY_TXYWXX.PJZT = '1') 
GROUP BY DKKBM) D 
LEFT JOIN CTE_JKRXX ON D.DKKBM = CTE_JKRXX.DKKBM
UNION

SELECT E.DKKBM,ZZJGDM,CTE_JKRMC AS JKRMC,0 AS DKHTBS,0.00 AS DKFSE,0.00 AS DKYE,0 AS JJBS,0 AS BLBS,0.00 AS BLFSE,0.00 AS BLYE,0 AS PJTXBS,0.00 AS PJTXFSE,0.00 AS PJTXYE,MYRZXYBS,0.00 AS MYRZFSE,0.00 AS MYRZYE,0 AS MYRZYWBS,0 AS XYZBS,0.00 AS XYZFSE,0.00 AS XYZYE,0 AS BHBS,0.00 AS BHFSE,0.00 AS BHYE,0 AS CDHPBS,0.00 AS CDHPFSE,0.00 AS CDHPYE,0 AS GKSXBS,0.00 AS GKSXFSE,0 AS BZHTBS,0.00 AS BZFSE,0.00 AS BZYE,0 AS DYHTBS,0.00 AS DYFSE,0.00 AS DYYE,0 AS ZYHTBS,0.00 AS ZYFSE,0.00 AS ZYYE,0 AS DIANKUANBS,0.00 AS DIANKUANFSE,0.00 AS DIANKUANYE,0.00 AS BNQXYE,0.00 AS BWQXYE,p_REPORTINST AS DJJGDM,p_ENDDATE AS SJJZRQ FROM (
SELECT DKKBM,COUNT(1) AS MYRZXYBS FROM (
SELECT DKKBM,FOREIGNID,MAX(QY_RZXYXX.EXTEND2) AS EXTEND2 FROM QY_RZXYXX,QY_MYRZ_JC,REPORTINSTSUBINFO WHERE QY_RZXYXX.FOREIGNID = QY_MYRZ_JC.AUTOID AND INSTINFO = STRINSTCODE AND QY_RZXYXX.EXTEND2 <= p_ENDDATE AND strReportInstCode = p_REPORTINST AND XXJLCZLX = '1' AND QY_RZXYXX.RPTFEEDBACKTYPE = '2' GROUP BY DKKBM,FOREIGNID) TEMP WHERE NOT EXISTS(
SELECT * FROM QY_RZXYXX WHERE QY_RZXYXX.FOREIGNID = TEMP.FOREIGNID AND QY_RZXYXX.EXTEND2 = TEMP.EXTEND2 AND QY_RZXYXX.XYYXZT = '2') 
GROUP BY DKKBM) E 
LEFT JOIN CTE_JKRXX ON E.DKKBM = CTE_JKRXX.DKKBM
UNION

SELECT F.DKKBM,ZZJGDM,CTE_JKRMC AS JKRMC,0 AS DKHTBS,0.00 AS DKFSE,0.00 AS DKYE,0 AS JJBS,0 AS BLBS,0.00 AS BLFSE,0.00 AS BLYE,0 AS PJTXBS,0.00 AS PJTXFSE,0.00 AS PJTXYE,0 AS MYRZXYBS,MYRZFSE,MYRZYE,MYRZYWBS,0 AS XYZBS,0.00 AS XYZFSE,0.00 AS XYZYE,0 AS BHBS,0.00 AS BHFSE,0.00 AS BHYE,0 AS CDHPBS,0.00 AS CDHPFSE,0.00 AS CDHPYE,0 AS GKSXBS,0.00 AS GKSXFSE,0 AS BZHTBS,0.00 AS BZFSE,0.00 AS BZYE,0 AS DYHTBS,0.00 AS DYFSE,0.00 AS DYYE,0 AS ZYHTBS,0.00 AS ZYFSE,0.00 AS ZYYE,0 AS DIANKUANBS,0.00 AS DIANKUANFSE,0.00 AS DIANKUANYE,0.00 AS BNQXYE,0.00 AS BWQXYE,p_REPORTINST AS DJJGDM,p_ENDDATE AS SJJZRQ FROM (
SELECT DKKBM,SUM(CAST(RZJE AS DECIMAL(17,2))) AS MYRZFSE,SUM(CAST(RZYE AS DECIMAL(17,2))) AS MYRZYE,COUNT(1) AS MYRZYWBS FROM (
SELECT FOREIGNID,RZJE,RZYE,RZYWBH FROM QY_RZYWXX WHERE EXISTS(
SELECT * FROM (SELECT FOREIGNID,RZYWBH,MAX(QY_RZYWXX.EXTEND2) AS EXTEND2 FROM QY_RZYWXX,QY_MYRZ_JC,REPORTINSTSUBINFO WHERE QY_RZYWXX.FOREIGNID = QY_MYRZ_JC.AUTOID AND INSTINFO = STRINSTCODE AND QY_RZYWXX.EXTEND2 <= p_ENDDATE AND strReportInstCode = p_REPORTINST AND XXJLCZLX = '1' AND QY_RZYWXX.RPTFEEDBACKTYPE = '2' GROUP BY FOREIGNID,RZYWBH) TEMP 
WHERE QY_RZYWXX.FOREIGNID = TEMP.FOREIGNID AND QY_RZYWXX.RZYWBH = TEMP.RZYWBH AND QY_RZYWXX.EXTEND2 = TEMP.EXTEND2 AND QY_RZYWXX.RZYE <> '0.00')) TEMP2,QY_MYRZ_JC 
WHERE TEMP2.FOREIGNID = QY_MYRZ_JC.AUTOID 
GROUP BY DKKBM) F 
LEFT JOIN CTE_JKRXX ON F.DKKBM = CTE_JKRXX.DKKBM
UNION

SELECT G.DKKBM,ZZJGDM,CTE_JKRMC AS JKRMC,0 AS DKHTBS,0.00 AS DKFSE,0.00 AS DKYE,0 AS JJBS,0 AS BLBS,0.00 AS BLFSE,0.00 AS BLYE,0 AS PJTXBS,0.00 AS PJTXFSE,0.00 AS PJTXYE,0 AS MYRZXYBS,0.00 AS MYRZFSE,0.00 AS MYRZYE,0 AS MYRZYWBS,XYZBS,XYZFSE,XYZYE,0 AS BHBS,0.00 AS BHFSE,0.00 AS BHYE,0 AS CDHPBS,0.00 AS CDHPFSE,0.00 AS CDHPYE,0 AS GKSXBS,0.00 AS GKSXFSE,0 AS BZHTBS,0.00 AS BZFSE,0.00 AS BZYE,0 AS DYHTBS,0.00 AS DYFSE,0.00 AS DYYE,0 AS ZYHTBS,0.00 AS ZYFSE,0.00 AS ZYYE,0 AS DIANKUANBS,0.00 AS DIANKUANFSE,0.00 AS DIANKUANYE,0.00 AS BNQXYE,0.00 AS BWQXYE,p_REPORTINST AS DJJGDM,p_ENDDATE AS SJJZRQ FROM (
SELECT DKKBM,COUNT(1) AS XYZBS,SUM(CAST(KZJE AS DECIMAL(17,2))) AS XYZFSE,SUM(CAST(XYZYE AS DECIMAL(17,2))) AS XYZYE FROM QY_XYZYWXX WHERE EXISTS (
SELECT * FROM (SELECT FOREIGNID,MAX(QY_XYZYWXX.EXTEND2) AS EXTEND2 FROM QY_XYZYWXX,QY_XYZYW_JC,REPORTINSTSUBINFO WHERE QY_XYZYWXX.FOREIGNID = QY_XYZYW_JC.AUTOID AND INSTINFO = STRINSTCODE AND QY_XYZYWXX.EXTEND2 <= p_ENDDATE AND strReportInstCode = p_REPORTINST AND XXJLCZLX = '1' AND QY_XYZYWXX.RPTFEEDBACKTYPE = '2' GROUP BY FOREIGNID) TEMP 
WHERE QY_XYZYWXX.FOREIGNID = TEMP.FOREIGNID AND QY_XYZYWXX.EXTEND2 = TEMP.EXTEND2 AND QY_XYZYWXX.XYZZT = '1') 
GROUP BY DKKBM) G 
LEFT JOIN CTE_JKRXX ON G.DKKBM = CTE_JKRXX.DKKBM
UNION

SELECT H.DKKBM,ZZJGDM,CTE_JKRMC AS JKRMC,0 AS DKHTBS,0.00 AS DKFSE,0.00 AS DKYE,0 AS JJBS,0 AS BLBS,0.00 AS BLFSE,0.00 AS BLYE,0 AS PJTXBS,0.00 AS PJTXFSE,0.00 AS PJTXYE,0 AS MYRZXYBS,0.00 AS MYRZFSE,0.00 AS MYRZYE,0 AS MYRZYWBS,0 AS XYZBS,0.00 AS XYZFSE,0.00 AS XYZYE,BHBS,BHFSE,BHYE,0 AS CDHPBS,0.00 AS CDHPFSE,0.00 AS CDHPYE,0 AS GKSXBS,0.00 AS GKSXFSE,0 AS BZHTBS,0.00 AS BZFSE,0.00 AS BZYE,0 AS DYHTBS,0.00 AS DYFSE,0.00 AS DYYE,0 AS ZYHTBS,0.00 AS ZYFSE,0.00 AS ZYYE,0 AS DIANKUANBS,0.00 AS DIANKUANFSE,0.00 AS DIANKUANYE,0.00 AS BNQXYE,0.00 AS BWQXYE,p_REPORTINST AS DJJGDM,p_ENDDATE AS SJJZRQ FROM (
SELECT DKKBM,COUNT(1) AS BHBS,SUM(CAST(BHJE AS DECIMAL(17,2))) AS BHFSE,SUM(CAST(BHYE AS DECIMAL(17,2))) AS BHYE FROM QY_BHYWXX WHERE EXISTS (
SELECT * FROM (SELECT FOREIGNID,MAX(QY_BHYWXX.EXTEND2) AS EXTEND2 FROM QY_BHYWXX,QY_BHYW_JC,REPORTINSTSUBINFO WHERE QY_BHYWXX.FOREIGNID = QY_BHYW_JC.AUTOID AND INSTINFO = STRINSTCODE AND QY_BHYWXX.EXTEND2 <= p_ENDDATE AND strReportInstCode = p_REPORTINST AND XXJLCZLX = '1' AND QY_BHYWXX.RPTFEEDBACKTYPE = '2' GROUP BY FOREIGNID) TEMP 
WHERE QY_BHYWXX.FOREIGNID = TEMP.FOREIGNID AND QY_BHYWXX.EXTEND2 = TEMP.EXTEND2 AND QY_BHYWXX.BHZT = '1') 
GROUP BY DKKBM) H 
LEFT JOIN CTE_JKRXX ON H.DKKBM = CTE_JKRXX.DKKBM
UNION

SELECT I.DKKBM,ZZJGDM,CTE_JKRMC AS JKRMC,0 AS DKHTBS,0.00 AS DKFSE,0.00 AS DKYE,0 AS JJBS,0 AS BLBS,0.00 AS BLFSE,0.00 AS BLYE,0 AS PJTXBS,0.00 AS PJTXFSE,0.00 AS PJTXYE,0 AS MYRZXYBS,0.00 AS MYRZFSE,0.00 AS MYRZYE,0 AS MYRZYWBS,0 AS XYZBS,0.00 AS XYZFSE,0.00 AS XYZYE,0 AS BHBS,0.00 AS BHFSE,0.00 AS BHYE,CDHPBS,CDHPFSE,CDHPYE,0 AS GKSXBS,0.00 AS GKSXFSE,0 AS BZHTBS,0.00 AS BZFSE,0.00 AS BZYE,0 AS DYHTBS,0.00 AS DYFSE,0.00 AS DYYE,0 AS ZYHTBS,0.00 AS ZYFSE,0.00 AS ZYYE,0 AS DIANKUANBS,0.00 AS DIANKUANFSE,0.00 AS DIANKUANYE,0.00 AS BNQXYE,0.00 AS BWQXYE,p_REPORTINST AS DJJGDM,p_ENDDATE AS SJJZRQ FROM (
SELECT DKKBM,COUNT(1) AS CDHPBS,SUM(CAST(HPJE AS DECIMAL(17,2))) AS CDHPFSE,SUM(CAST(HPJE AS DECIMAL(17,2))) AS CDHPYE FROM QY_HPYWXX WHERE EXISTS (
SELECT * FROM (SELECT FOREIGNID,MAX(QY_HPYWXX.EXTEND2) AS EXTEND2 FROM QY_HPYWXX,QY_YHCDHP_JC,REPORTINSTSUBINFO WHERE QY_HPYWXX.FOREIGNID = QY_YHCDHP_JC.AUTOID AND INSTINFO = STRINSTCODE AND QY_HPYWXX.EXTEND2 <= p_ENDDATE AND strReportInstCode = p_REPORTINST AND XXJLCZLX = '1' AND QY_HPYWXX.RPTFEEDBACKTYPE = '2' GROUP BY FOREIGNID) TEMP 
WHERE QY_HPYWXX.FOREIGNID = TEMP.FOREIGNID AND QY_HPYWXX.EXTEND2 = TEMP.EXTEND2 AND QY_HPYWXX.HPZT = '1') 
GROUP BY DKKBM) I 
LEFT JOIN CTE_JKRXX ON I.DKKBM = CTE_JKRXX.DKKBM
UNION

SELECT J.DKKBM,ZZJGDM,CTE_JKRMC AS JKRMC,0 AS DKHTBS,0.00 AS DKFSE,0.00 AS DKYE,0 AS JJBS,0 AS BLBS,0.00 AS BLFSE,0.00 AS BLYE,0 AS PJTXBS,0.00 AS PJTXFSE,0.00 AS PJTXYE,0 AS MYRZXYBS,0.00 AS MYRZFSE,0.00 AS MYRZYE,0 AS MYRZYWBS,0 AS XYZBS,0.00 AS XYZFSE,0.00 AS XYZYE,0 AS BHBS,0.00 AS BHFSE,0.00 AS BHYE,0 AS CDHPBS,0.00 AS CDHPFSE,0.00 AS CDHPYE,GKSXBS,GKSXFSE,0 AS BZHTBS,0.00 AS BZFSE,0.00 AS BZYE,0 AS DYHTBS,0.00 AS DYFSE,0.00 AS DYYE,0 AS ZYHTBS,0.00 AS ZYFSE,0.00 AS ZYYE,0 AS DIANKUANBS,0.00 AS DIANKUANFSE,0.00 AS DIANKUANYE,0.00 AS BNQXYE,0.00 AS BWQXYE,p_REPORTINST AS DJJGDM,p_ENDDATE AS SJJZRQ FROM (
SELECT DKKBM,COUNT(1) AS GKSXBS,SUM(CAST(SXED AS DECIMAL(17,2))) AS GKSXFSE FROM QY_SXYWXX WHERE EXISTS (
SELECT * FROM (SELECT FOREIGNID,MAX(QY_SXYWXX.EXTEND2) AS EXTEND2 FROM QY_SXYWXX,QY_GKSX_JC,REPORTINSTSUBINFO WHERE QY_SXYWXX.FOREIGNID = QY_GKSX_JC.AUTOID AND INSTINFO = STRINSTCODE AND QY_SXYWXX.EXTEND2 <= p_ENDDATE AND strReportInstCode = p_REPORTINST AND XXJLCZLX = '1' AND QY_SXYWXX.RPTFEEDBACKTYPE = '2' GROUP BY FOREIGNID) TEMP 
WHERE QY_SXYWXX.FOREIGNID = TEMP.FOREIGNID AND QY_SXYWXX.EXTEND2 = TEMP.EXTEND2 AND QY_SXYWXX.SXEDZXSXRQ > p_ENDDATE AND QY_SXYWXX.SXZZRQ > p_ENDDATE) 
GROUP BY DKKBM) J 
LEFT JOIN CTE_JKRXX ON J.DKKBM = CTE_JKRXX.DKKBM
UNION

SELECT K.BZRDDKKBM AS DKKBM,ZZJGDM,BZRMC AS JKRMC,0 AS DKHTBS,0.00 AS DKFSE,0.00 AS DKYE,0 AS JJBS,0 AS BLBS,0.00 AS BLFSE,0.00 AS BLYE,0 AS PJTXBS,0.00 AS PJTXFSE,0.00 AS PJTXYE,0 AS MYRZXYBS,0.00 AS MYRZFSE,0.00 AS MYRZYE,0 AS MYRZYWBS,0 AS XYZBS,0.00 AS XYZFSE,0.00 AS XYZYE,0 AS BHBS,0.00 AS BHFSE,0.00 AS BHYE,0 AS CDHPBS,0.00 AS CDHPFSE,0.00 AS CDHPYE,0 AS GKSXBS,0.00 AS GKSXFSE,BZHTBS,BZFSE,BZYE,0 AS DYHTBS,0.00 AS DYFSE,0.00 AS DYYE,0 AS ZYHTBS,0.00 AS ZYFSE,0.00 AS ZYYE,0 AS DIANKUANBS,0.00 AS DIANKUANFSE,0.00 AS DIANKUANYE,0.00 AS BNQXYE,0.00 AS BWQXYE,p_REPORTINST AS DJJGDM,p_ENDDATE AS SJJZRQ FROM (
SELECT BZRDDKKBM,MAX(BZRMC) AS BZRMC,COUNT(1) AS BZHTBS,SUM(CAST(BZJE AS DECIMAL(17,2))) AS BZFSE,SUM(CAST(BZJE AS DECIMAL(17,2))) AS BZYE FROM (
SELECT BZRDDKKBM,MAX(BZRMC) AS BZRMC,MAX(BZJE) AS BZJE FROM QY_DBHTXX WHERE EXISTS (
SELECT * FROM (SELECT BZRDDKKBM,BZHTBH,MAX(QY_DBHTXX.EXTEND2) AS EXTEND2 FROM QY_DBHTXX,QY_DBXX_JC,REPORTINSTSUBINFO WHERE QY_DBHTXX.FOREIGNID = QY_DBXX_JC.AUTOID AND INSTINFO = STRINSTCODE AND QY_DBHTXX.EXTEND2 <= p_ENDDATE AND strReportInstCode = p_REPORTINST AND XXJLCZLX = '1' AND QY_DBHTXX.RPTFEEDBACKTYPE = '2' AND QY_DBHTXX.HTYXZT = '1' GROUP BY BZRDDKKBM,BZHTBH) TEMP 
WHERE QY_DBHTXX.BZRDDKKBM = TEMP.BZRDDKKBM AND QY_DBHTXX.BZHTBH = TEMP.BZHTBH AND QY_DBHTXX.EXTEND2 = TEMP.EXTEND2) GROUP BY BZRDDKKBM,BZHTBH) TEMP2
GROUP BY BZRDDKKBM) K 
LEFT JOIN CTE_JKRXX ON K.BZRDDKKBM = CTE_JKRXX.DKKBM
UNION

SELECT L.DYRDKKBM AS DKKBM,ZZJGDM,DYRMC AS JKRMC,0 AS DKHTBS,0.00 AS DKFSE,0.00 AS DKYE,0 AS JJBS,0 AS BLBS,0.00 AS BLFSE,0.00 AS BLYE,0 AS PJTXBS,0.00 AS PJTXFSE,0.00 AS PJTXYE,0 AS MYRZXYBS,0.00 AS MYRZFSE,0.00 AS MYRZYE,0 AS MYRZYWBS,0 AS XYZBS,0.00 AS XYZFSE,0.00 AS XYZYE,0 AS BHBS,0.00 AS BHFSE,0.00 AS BHYE,0 AS CDHPBS,0.00 AS CDHPFSE,0.00 AS CDHPYE,0 AS GKSXBS,0.00 AS GKSXFSE,0 AS BZHTBS,0.00 AS BZFSE,0.00 AS BZYE,DYHTBS,DYFSE,DYYE,0 AS ZYHTBS,0.00 AS ZYFSE,0.00 AS ZYYE,0 AS DIANKUANBS,0.00 AS DIANKUANFSE,0.00 AS DIANKUANYE,0.00 AS BNQXYE,0.00 AS BWQXYE,p_REPORTINST AS DJJGDM,p_ENDDATE AS SJJZRQ FROM (
SELECT DYRDKKBM,MAX(DYRMC) AS DYRMC,COUNT(1) AS DYHTBS,SUM(CAST(DYJE AS DECIMAL(17,2))) AS DYFSE,SUM(CAST(DYJE AS DECIMAL(17,2))) AS DYYE FROM (
SELECT DYRDKKBM,MAX(DYRMC) AS DYRMC,SUM(CAST(DYJE AS DECIMAL(17,2))) AS DYJE FROM (
SELECT DYRDKKBM,MAX(DYRMC) AS DYRMC,DYHTBM,MAX(DYJE) AS DYJE FROM QY_DYHTXX WHERE EXISTS (
SELECT * FROM (SELECT DYRDKKBM,DYHTBM,DYXH,MAX(QY_DYHTXX.EXTEND2) AS EXTEND2 FROM QY_DYHTXX,QY_DBXX_JC,REPORTINSTSUBINFO WHERE QY_DYHTXX.FOREIGNID = QY_DBXX_JC.AUTOID AND INSTINFO = STRINSTCODE AND QY_DYHTXX.EXTEND2 <= p_ENDDATE AND strReportInstCode = p_REPORTINST AND XXJLCZLX = '1' AND QY_DYHTXX.RPTFEEDBACKTYPE = '2' AND QY_DYHTXX.HTYXZT = '1' GROUP BY DYRDKKBM,DYHTBM,DYXH) TEMP 
WHERE QY_DYHTXX.DYRDKKBM = TEMP.DYRDKKBM AND QY_DYHTXX.DYHTBM = TEMP.DYHTBM AND QY_DYHTXX.DYXH = TEMP.DYXH AND QY_DYHTXX.EXTEND2 = TEMP.EXTEND2) GROUP BY DYRDKKBM,DYHTBM,DYXH) TEMP2
GROUP BY DYRDKKBM,DYHTBM) TEMP3 
GROUP BY DYRDKKBM) L 
LEFT JOIN CTE_JKRXX ON L.DYRDKKBM = CTE_JKRXX.DKKBM
UNION 

SELECT M.CZRDDKKBM AS DKKBM,ZZJGDM,CZRMC AS JKRMC,0 AS DKHTBS,0.00 AS DKFSE,0.00 AS DKYE,0 AS JJBS,0 AS BLBS,0.00 AS BLFSE,0.00 AS BLYE,0 AS PJTXBS,0.00 AS PJTXFSE,0.00 AS PJTXYE,0 AS MYRZXYBS,0.00 AS MYRZFSE,0.00 AS MYRZYE,0 AS MYRZYWBS,0 AS XYZBS,0.00 AS XYZFSE,0.00 AS XYZYE,0 AS BHBS,0.00 AS BHFSE,0.00 AS BHYE,0 AS CDHPBS,0.00 AS CDHPFSE,0.00 AS CDHPYE,0 AS GKSXBS,0.00 AS GKSXFSE,0 AS BZHTBS,0.00 AS BZFSE,0.00 AS BZYE,0 AS DYHTBS,0.00 AS DYFSE,0.00 AS DYYE,ZYHTBS,ZYFSE,ZYYE,0 AS DIANKUANBS,0.00 AS DIANKUANFSE,0.00 AS DIANKUANYE,0.00 AS BNQXYE,0.00 AS BWQXYE,p_REPORTINST AS DJJGDM,p_ENDDATE AS SJJZRQ FROM (
SELECT CZRDDKKBM,MAX(CZRMC) AS CZRMC,COUNT(1) AS ZYHTBS,SUM(CAST(ZYJE AS DECIMAL(17,2))) AS ZYFSE,SUM(CAST(ZYJE AS DECIMAL(17,2))) AS ZYYE FROM (
SELECT CZRDDKKBM,MAX(CZRMC) AS CZRMC,SUM(CAST(ZYJE AS DECIMAL(17,2))) AS ZYJE FROM (
SELECT CZRDDKKBM,MAX(CZRMC) AS CZRMC,ZYHTBH,MAX(ZYJE) AS ZYJE FROM QY_ZYHTXX WHERE EXISTS (
SELECT * FROM (SELECT CZRDDKKBM,ZYHTBH,ZYXH,MAX(QY_ZYHTXX.EXTEND2) AS EXTEND2 FROM QY_ZYHTXX,QY_DBXX_JC,REPORTINSTSUBINFO WHERE QY_ZYHTXX.FOREIGNID = QY_DBXX_JC.AUTOID AND INSTINFO = STRINSTCODE AND QY_ZYHTXX.EXTEND2 <= p_ENDDATE AND strReportInstCode = p_REPORTINST AND XXJLCZLX = '1' AND QY_ZYHTXX.RPTFEEDBACKTYPE = '2' AND QY_ZYHTXX.HTYXZT = '1' GROUP BY CZRDDKKBM,ZYHTBH,ZYXH) TEMP 
WHERE QY_ZYHTXX.CZRDDKKBM = TEMP.CZRDDKKBM AND QY_ZYHTXX.ZYHTBH = TEMP.ZYHTBH AND QY_ZYHTXX.ZYXH = TEMP.ZYXH AND QY_ZYHTXX.EXTEND2 = TEMP.EXTEND2) GROUP BY CZRDDKKBM,ZYHTBH,ZYXH) TEMP2 
GROUP BY CZRDDKKBM,ZYHTBH) TEMP3
GROUP BY CZRDDKKBM) M 
LEFT JOIN CTE_JKRXX ON M.CZRDDKKBM = CTE_JKRXX.DKKBM
UNION

SELECT N.DKKBM AS DKKBM,ZZJGDM,CTE_JKRMC AS JKRMC,0 AS DKHTBS,0.00 AS DKFSE,0.00 AS DKYE,0 AS JJBS,0 AS BLBS,0.00 AS BLFSE,0.00 AS BLYE,0 AS PJTXBS,0.00 AS PJTXFSE,0.00 AS PJTXYE,0 AS MYRZXYBS,0.00 AS MYRZFSE,0.00 AS MYRZYE,0 AS MYRZYWBS,0 AS XYZBS,0.00 AS XYZFSE,0.00 AS XYZYE,0 AS BHBS,0.00 AS BHFSE,0.00 AS BHYE,0 AS CDHPBS,0.00 AS CDHPFSE,0.00 AS CDHPYE,0 AS GKSXBS,0.00 AS GKSXFSE,0 AS BZHTBS,0.00 AS BZFSE,0.00 AS BZYE,0 AS DYHTBS,0.00 AS DYFSE,0.00 AS DYYE,0 AS ZYHTBS,0.00 AS ZYFSE,0.00 AS ZYYE,DIANKUANBS,DIANKUANFSE,DIANKUANYE,0.00 AS BNQXYE,0.00 AS BWQXYE,p_REPORTINST AS DJJGDM,p_ENDDATE AS SJJZRQ FROM (
SELECT DKKBM,COUNT(1) AS DIANKUANBS,SUM(CAST(DKJE AS DECIMAL(17,2))) AS DIANKUANFSE,SUM(CAST(DKYE AS DECIMAL(17,2))) AS DIANKUANYE FROM QY_DKYWXX WHERE EXISTS (
SELECT * FROM (SELECT FOREIGNID,MAX(QY_DKYWXX.EXTEND2) AS EXTEND2 FROM QY_DKYWXX,QY_DKXX_JC,REPORTINSTSUBINFO WHERE QY_DKYWXX.FOREIGNID = QY_DKXX_JC.AUTOID AND INSTINFO = STRINSTCODE AND QY_DKYWXX.EXTEND2 <= p_ENDDATE AND strReportInstCode = p_REPORTINST AND XXJLCZLX = '1' AND QY_DKYWXX.RPTFEEDBACKTYPE = '2' GROUP BY FOREIGNID) TEMP 
WHERE QY_DKYWXX.FOREIGNID = TEMP.FOREIGNID AND QY_DKYWXX.EXTEND2 = TEMP.EXTEND2 AND QY_DKYWXX.DKYE <> '0.00') 
GROUP BY DKKBM) N 
LEFT JOIN CTE_JKRXX ON N.DKKBM = CTE_JKRXX.DKKBM
UNION

SELECT O.DKKBM AS DKKBM,ZZJGDM,CTE_JKRMC AS JKRMC,0 AS DKHTBS,0.00 AS DKFSE,0.00 AS DKYE,0 AS JJBS,0 AS BLBS,0.00 AS BLFSE,0.00 AS BLYE,0 AS PJTXBS,0.00 AS PJTXFSE,0.00 AS PJTXYE,0 AS MYRZXYBS,0.00 AS MYRZFSE,0.00 AS MYRZYE,0 AS MYRZYWBS,0 AS XYZBS,0.00 AS XYZFSE,0.00 AS XYZYE,0 AS BHBS,0.00 AS BHFSE,0.00 AS BHYE,0 AS CDHPBS,0.00 AS CDHPFSE,0.00 AS CDHPYE,0 AS GKSXBS,0.00 AS GKSXFSE,0 AS BZHTBS,0.00 AS BZFSE,0.00 AS BZYE,0 AS DYHTBS,0.00 AS DYFSE,0.00 AS DYYE,0 AS ZYHTBS,0.00 AS ZYFSE,0.00 AS ZYYE,0 AS DIANKUANBS,0.00 AS DIANKUANFSE,0.00 AS DIANKUANYE,BNQXYE,0.00 AS BWQXYE,p_REPORTINST AS DJJGDM,p_ENDDATE AS SJJZRQ FROM (
SELECT DKKBM,SUM(CAST(QXYE AS DECIMAL(17,2))) AS BNQXYE FROM (
SELECT FOREIGNID,QXYE FROM QY_QXYWXX WHERE EXISTS(
SELECT * FROM (SELECT FOREIGNID,MAX(QY_QXYWXX.EXTEND2) AS EXTEND2 FROM QY_QXYWXX,QY_QXXX_JC,REPORTINSTSUBINFO WHERE QY_QXYWXX.FOREIGNID = QY_QXXX_JC.AUTOID AND INSTINFO = STRINSTCODE AND QY_QXYWXX.EXTEND2 <= p_ENDDATE AND strReportInstCode = p_REPORTINST AND XXJLCZLX = '1' AND QY_QXYWXX.RPTFEEDBACKTYPE = '2' GROUP BY FOREIGNID) TEMP 
WHERE QY_QXYWXX.FOREIGNID = TEMP.FOREIGNID AND QY_QXYWXX.EXTEND2 = TEMP.EXTEND2 AND QY_QXYWXX.QXYE <> '0.00' AND QY_QXYWXX.QXLX = '1')) TEMP2,QY_QXXX_JC WHERE TEMP2.FOREIGNID = QY_QXXX_JC.AUTOID 
GROUP BY DKKBM) O 
LEFT JOIN CTE_JKRXX ON O.DKKBM = CTE_JKRXX.DKKBM
UNION

SELECT P.DKKBM AS DKKBM,ZZJGDM,CTE_JKRMC AS JKRMC,0 AS DKHTBS,0.00 AS DKFSE,0.00 AS DKYE,0 AS JJBS,0 AS BLBS,0.00 AS BLFSE,0.00 AS BLYE,0 AS PJTXBS,0.00 AS PJTXFSE,0.00 AS PJTXYE,0 AS MYRZXYBS,0.00 AS MYRZFSE,0.00 AS MYRZYE,0 AS MYRZYWBS,0 AS XYZBS,0.00 AS XYZFSE,0.00 AS XYZYE,0 AS BHBS,0.00 AS BHFSE,0.00 AS BHYE,0 AS CDHPBS,0.00 AS CDHPFSE,0.00 AS CDHPYE,0 AS GKSXBS,0.00 AS GKSXFSE,0 AS BZHTBS,0.00 AS BZFSE,0.00 AS BZYE,0 AS DYHTBS,0.00 AS DYFSE,0.00 AS DYYE,0 AS ZYHTBS,0.00 AS ZYFSE,0.00 AS ZYYE,0 AS DIANKUANBS,0.00 AS DIANKUANFSE,0.00 AS DIANKUANYE,0.00 AS BNQXYE,BWQXYE,p_REPORTINST AS DJJGDM,p_ENDDATE AS SJJZRQ FROM (
SELECT DKKBM,SUM(CAST(QXYE AS DECIMAL(17,2))) AS BWQXYE FROM (
SELECT FOREIGNID,QXYE FROM QY_QXYWXX WHERE EXISTS(
SELECT * FROM (SELECT FOREIGNID,MAX(QY_QXYWXX.EXTEND2) AS EXTEND2 FROM QY_QXYWXX,QY_QXXX_JC,REPORTINSTSUBINFO WHERE QY_QXYWXX.FOREIGNID = QY_QXXX_JC.AUTOID AND INSTINFO = STRINSTCODE AND QY_QXYWXX.EXTEND2 <= p_ENDDATE AND strReportInstCode = p_REPORTINST AND XXJLCZLX = '1' AND QY_QXYWXX.RPTFEEDBACKTYPE = '2' GROUP BY FOREIGNID) TEMP 
WHERE QY_QXYWXX.FOREIGNID = TEMP.FOREIGNID AND QY_QXYWXX.EXTEND2 = TEMP.EXTEND2 AND QY_QXYWXX.QXYE <> '0.00' AND QY_QXYWXX.QXLX = '2')) TEMP2,QY_QXXX_JC WHERE TEMP2.FOREIGNID = QY_QXXX_JC.AUTOID 
GROUP BY DKKBM) P 
LEFT JOIN CTE_JKRXX ON P.DKKBM = CTE_JKRXX.DKKBM
UNION

SELECT ZJLX AS DKKBM,ZJHM AS ZZJGDM,MAX(BZRMC) AS JKRMC,0 AS DKHTBS,0.00 AS DKFSE,0.00 AS DKYE,0 AS JJBS,0 AS BLBS,0.00 AS BLFSE,0.00 AS BLYE,0 AS PJTXBS,0.00 AS PJTXFSE,0.00 AS PJTXYE,0 AS MYRZXYBS,0.00 AS MYRZFSE,0.00 AS MYRZYE,0 AS MYRZYWBS,0 AS XYZBS,0.00 AS XYZFSE,0.00 AS XYZYE,0 AS BHBS,0.00 AS BHFSE,0.00 AS BHYE,0 AS CDHPBS,0.00 AS CDHPFSE,0.00 AS CDHPYE,0 AS GKSXBS,0.00 AS GKSXFSE,COUNT(1) AS BZHTBS,SUM(CAST(BZJE AS DECIMAL(17,2))) AS BZFSE,SUM(CAST(BZJE AS DECIMAL(17,2))) AS BZYE,0 AS DYHTBS,0.00 AS DYFSE,0.00 AS DYYE,0 AS ZYHTBS,0.00 AS ZYFSE,0.00 AS ZYYE,0 AS DIANKUANBS,0.00 AS DIANKUANFSE,0.00 AS DIANKUANYE,0.00 AS BNQXYE,0.00 AS BWQXYE,p_REPORTINST AS DJJGDM,p_ENDDATE AS SJJZRQ FROM (
SELECT ZJLX,ZJHM,MAX(BZRMC) AS BZRMC,MAX(BZJE) AS BZJE FROM QY_ZRRBZHTXX WHERE EXISTS (
SELECT * FROM (SELECT ZJLX,ZJHM,BZHTBH,MAX(QY_ZRRBZHTXX.EXTEND2) AS EXTEND2 FROM QY_ZRRBZHTXX,QY_DBXX_JC,REPORTINSTSUBINFO WHERE QY_ZRRBZHTXX.FOREIGNID = QY_DBXX_JC.AUTOID AND INSTINFO = STRINSTCODE AND QY_ZRRBZHTXX.EXTEND2 <= p_ENDDATE AND strReportInstCode = p_REPORTINST AND XXJLCZLX = '1' AND QY_ZRRBZHTXX.RPTFEEDBACKTYPE = '2' AND QY_ZRRBZHTXX.HTYXZT = '1' GROUP BY ZJLX,ZJHM,BZHTBH) TEMP 
WHERE QY_ZRRBZHTXX.ZJLX = TEMP.ZJLX AND QY_ZRRBZHTXX.ZJHM = TEMP.ZJHM AND QY_ZRRBZHTXX.BZHTBH = TEMP.BZHTBH AND QY_ZRRBZHTXX.EXTEND2 = TEMP.EXTEND2) GROUP BY ZJLX,ZJHM,BZHTBH) TEMP2
GROUP BY ZJLX,ZJHM
UNION

SELECT ZJLX AS DKKBM,ZJHM AS ZZJGDM,MAX(DYRMC) AS JKRMC,0 AS DKHTBS,0.00 AS DKFSE,0.00 AS DKYE,0 AS JJBS,0 AS BLBS,0.00 AS BLFSE,0.00 AS BLYE,0 AS PJTXBS,0.00 AS PJTXFSE,0.00 AS PJTXYE,0 AS MYRZXYBS,0.00 AS MYRZFSE,0.00 AS MYRZYE,0 AS MYRZYWBS,0 AS XYZBS,0.00 AS XYZFSE,0.00 AS XYZYE,0 AS BHBS,0.00 AS BHFSE,0.00 AS BHYE,0 AS CDHPBS,0.00 AS CDHPFSE,0.00 AS CDHPYE,0 AS GKSXBS,0.00 AS GKSXFSE,0 AS BZHTBS,0.00 AS BZFSE,0.00 AS BZYE,COUNT(1) AS DYHTBS,SUM(DYJE) AS DYFSE,SUM(DYJE) AS DYYE,0 AS ZYHTBS,0.00 AS ZYFSE,0.00 AS ZYYE,0 AS DIANKUANBS,0.00 AS DIANKUANFSE,0.00 AS DIANKUANYE,0.00 AS BNQXYE,0.00 AS BWQXYE,p_REPORTINST AS DJJGDM,p_ENDDATE AS SJJZRQ FROM (
SELECT ZJLX,ZJHM,MAX(DYRMC) AS DYRMC,SUM(CAST(DYJE AS DECIMAL(17,2))) AS DYJE FROM (
SELECT ZJLX,ZJHM,MAX(DYRMC) AS DYRMC,DYHTBH,MAX(DYJE) AS DYJE FROM QY_ZRRDYHTXX WHERE EXISTS (
SELECT * FROM (SELECT ZJLX,ZJHM,DYHTBH,DYXH,MAX(QY_ZRRDYHTXX.EXTEND2) AS EXTEND2 FROM QY_ZRRDYHTXX,QY_DBXX_JC,REPORTINSTSUBINFO WHERE QY_ZRRDYHTXX.FOREIGNID = QY_DBXX_JC.AUTOID AND INSTINFO = STRINSTCODE AND QY_ZRRDYHTXX.EXTEND2 <= p_ENDDATE AND strReportInstCode = p_REPORTINST AND XXJLCZLX = '1' AND QY_ZRRDYHTXX.RPTFEEDBACKTYPE = '2' AND QY_ZRRDYHTXX.HTYXZT = '1' GROUP BY ZJLX,ZJHM,DYHTBH,DYXH) TEMP 
WHERE QY_ZRRDYHTXX.ZJLX = TEMP.ZJLX AND QY_ZRRDYHTXX.ZJHM = TEMP.ZJHM AND QY_ZRRDYHTXX.DYHTBH = TEMP.DYHTBH AND QY_ZRRDYHTXX.DYXH = TEMP.DYXH AND QY_ZRRDYHTXX.EXTEND2 = TEMP.EXTEND2) GROUP BY ZJLX,ZJHM,DYHTBH,DYXH) TEMP2 
GROUP BY ZJLX,ZJHM,DYHTBH) TEMP3
GROUP BY ZJLX,ZJHM
UNION

SELECT ZJLX AS DKKBM,ZJHM AS ZZJGDM,MAX(CZRMC) AS JKRMC,0 AS DKHTBS,0.00 AS DKFSE,0.00 AS DKYE,0 AS JJBS,0 AS BLBS,0.00 AS BLFSE,0.00 AS BLYE,0 AS PJTXBS,0.00 AS PJTXFSE,0.00 AS PJTXYE,0 AS MYRZXYBS,0.00 AS MYRZFSE,0.00 AS MYRZYE,0 AS MYRZYWBS,0 AS XYZBS,0.00 AS XYZFSE,0.00 AS XYZYE,0 AS BHBS,0.00 AS BHFSE,0.00 AS BHYE,0 AS CDHPBS,0.00 AS CDHPFSE,0.00 AS CDHPYE,0 AS GKSXBS,0.00 AS GKSXFSE,0 AS BZHTBS,0.00 AS BZFSE,0.00 AS BZYE,0 AS DYHTBS,0.00 AS DYFSE,0.00 AS DYYE,COUNT(1) AS ZYHTBS,SUM(ZYJE) AS ZYFSE,SUM(ZYJE) AS ZYYE,0 AS DIANKUANBS,0.00 AS DIANKUANFSE,0.00 AS DIANKUANYE,0.00 AS BNQXYE,0.00 AS BWQXYE,p_REPORTINST AS DJJGDM,p_ENDDATE AS SJJZRQ FROM (
SELECT ZJLX,ZJHM,MAX(CZRMC) AS CZRMC,SUM(CAST(ZYJE AS DECIMAL(17,2))) AS ZYJE FROM (
SELECT ZJLX,ZJHM,MAX(CZRMC) AS CZRMC,ZYHTBH,MAX(ZYJE) AS ZYJE FROM QY_ZRRZYHTXX WHERE EXISTS (
SELECT * FROM (SELECT ZJLX,ZJHM,ZYHTBH,ZYXH,MAX(QY_ZRRZYHTXX.EXTEND2) AS EXTEND2 FROM QY_ZRRZYHTXX,QY_DBXX_JC,REPORTINSTSUBINFO WHERE QY_ZRRZYHTXX.FOREIGNID = QY_DBXX_JC.AUTOID AND INSTINFO = STRINSTCODE AND QY_ZRRZYHTXX.EXTEND2 <= p_ENDDATE AND strReportInstCode = p_REPORTINST AND XXJLCZLX = '1' AND QY_ZRRZYHTXX.RPTFEEDBACKTYPE = '2' AND QY_ZRRZYHTXX.HTYXZT = '1' GROUP BY ZJLX,ZJHM,ZYHTBH,ZYXH) TEMP 
WHERE QY_ZRRZYHTXX.ZJLX = TEMP.ZJLX AND QY_ZRRZYHTXX.ZJHM = TEMP.ZJHM AND QY_ZRRZYHTXX.ZYHTBH = TEMP.ZYHTBH AND QY_ZRRZYHTXX.ZYXH = TEMP.ZYXH AND QY_ZRRZYHTXX.EXTEND2 = TEMP.EXTEND2) GROUP BY ZJLX,ZJHM,ZYHTBH,ZYXH) TEMP2 
GROUP BY ZJLX,ZJHM,ZYHTBH) TEMP3
GROUP BY ZJLX,ZJHM
) TEMPA
GROUP BY DKKBM,ZZJGDM) TEMPB;
END IF;


IF p_VERSION = '2.2'
THEN 

OPEN rt FOR
WITH CTE_JGXX
AS (
SELECT DKKBM,CASE WHEN JGZWMC IS NULL OR JGZWMC = '' THEN JGYWMC ELSE JGZWMC END AS CTE_JKRMC,ZZJGDM,MAX(JG_JBSX.EXTEND2) AS EXTEND2 FROM JG_JBSX,JG_JGJBXX_JC,REPORTINSTSUBINFO WHERE JG_JBSX.FOREIGNID = JG_JGJBXX_JC.AUTOID AND INSTINFO = STRINSTCODE AND JG_JBSX.EXTEND2 <= p_ENDDATE AND strReportInstCode = p_REPORTINST AND JG_JBSX.RPTFEEDBACKTYPE = '2' GROUP BY FOREIGNID,DKKBM,JGZWMC,JGYWMC,ZZJGDM
)
SELECT DKKBM,ZZJGDM,JKRMC,CASE WHEN DKHTBS = 0 AND JJBS = 0 THEN NULL ELSE DKHTBS END AS DKHTBS,CASE WHEN DKHTBS = 0 AND JJBS = 0 THEN NULL ELSE DKFSE END AS DKFSE,CASE WHEN DKHTBS = 0 AND JJBS = 0 THEN NULL ELSE DKYE END AS DKYE,CASE WHEN DKHTBS = 0 AND JJBS = 0 THEN NULL ELSE JJBS END AS JJBS,CASE WHEN BLBS = 0 THEN NULL ELSE BLBS END AS BLBS,CASE WHEN BLBS = 0 THEN NULL ELSE BLFSE END AS BLFSE,CASE WHEN BLBS = 0 THEN NULL ELSE BLYE END AS BLYE,CASE WHEN PJTXBS = 0 THEN NULL ELSE PJTXBS END AS PJTXBS,CASE WHEN PJTXBS = 0 THEN NULL ELSE PJTXFSE END AS PJTXFSE,CASE WHEN PJTXYE = 0 THEN NULL ELSE PJTXYE END AS PJTXYE,CASE WHEN MYRZXYBS = 0 AND MYRZYWBS = 0 THEN NULL ELSE MYRZXYBS END AS MYRZXYBS,CASE WHEN MYRZXYBS = 0 AND MYRZYWBS = 0 THEN NULL ELSE MYRZFSE END AS MYRZFSE,CASE WHEN MYRZXYBS = 0 AND MYRZYWBS = 0 THEN NULL ELSE MYRZYE END AS MYRZYE,CASE WHEN MYRZXYBS = 0 AND MYRZYWBS = 0 THEN NULL ELSE MYRZYWBS END AS MYRZYWBS,CASE WHEN XYZBS = 0 THEN NULL ELSE XYZBS END AS XYZBS,CASE WHEN XYZBS = 0 THEN NULL ELSE XYZFSE END AS XYZFSE,CASE WHEN XYZBS = 0 THEN NULL ELSE XYZYE END AS XYZYE,CASE WHEN BHBS = 0 THEN NULL ELSE BHBS END AS BHBS,CASE WHEN BHBS = 0 THEN NULL ELSE BHFSE END AS BHFSE,CASE WHEN BHBS = 0 THEN NULL ELSE BHYE END AS BHYE,CASE WHEN CDHPBS = 0 THEN NULL ELSE CDHPBS END AS CDHPBS,CASE WHEN CDHPBS = 0 THEN NULL ELSE CDHPFSE END AS CDHPFSE,CASE WHEN CDHPBS = 0 THEN NULL ELSE CDHPYE END AS CDHPYE,CASE WHEN GKSXBS = 0 THEN NULL ELSE GKSXBS END AS GKSXBS,CASE WHEN GKSXBS = 0 THEN NULL ELSE GKSXFSE END AS GKSXFSE,CASE WHEN BZHTBS = 0 THEN NULL ELSE BZHTBS END AS BZHTBS,CASE WHEN BZHTBS = 0 THEN NULL ELSE BZFSE END AS BZFSE,CASE WHEN BZHTBS = 0 THEN NULL ELSE BZYE END AS BZYE,CASE WHEN DYHTBS = 0 THEN NULL ELSE DYHTBS END AS DYHTBS,CASE WHEN DYHTBS = 0 THEN NULL ELSE DYFSE END AS DYFSE,CASE WHEN DYHTBS = 0 THEN NULL ELSE DYYE END AS DYYE,CASE WHEN ZYHTBS = 0 THEN NULL ELSE ZYHTBS END AS ZYHTBS,CASE WHEN ZYHTBS = 0 THEN NULL ELSE ZYFSE END AS ZYFSE,CASE WHEN ZYHTBS = 0 THEN NULL ELSE ZYYE END AS ZYYE,CASE WHEN DIANKUANBS = 0 THEN NULL ELSE DIANKUANBS END AS DIANKUANBS,CASE WHEN DIANKUANBS = 0 THEN NULL ELSE DIANKUANFSE END AS DIANKUANFSE,CASE WHEN DIANKUANBS = 0 THEN NULL ELSE DIANKUANYE END AS DIANKUANYE,CASE WHEN BNQXYE = 0 THEN NULL ELSE BNQXYE END AS BNQXYE,CASE WHEN BWQXYE = 0 THEN NULL ELSE BWQXYE END AS BWQXYE,DJJGDM,SUBSTR(SJJZRQ,1,4)||'-'||SUBSTR(SJJZRQ,5,2)||'-'||SUBSTR(SJJZRQ,7,2) AS SJJZRQ FROM (
SELECT DKKBM,ZZJGDM,'"'||MAX(JKRMC)||'"' AS JKRMC,SUM(DKHTBS) AS DKHTBS,SUM(DKFSE) AS DKFSE,SUM(DKYE) AS DKYE,SUM(JJBS) AS JJBS,SUM(BLBS) AS BLBS,SUM(BLFSE) AS BLFSE,SUM(BLYE) AS BLYE,SUM(PJTXBS) AS PJTXBS,SUM(PJTXFSE) AS PJTXFSE,SUM(PJTXYE) AS PJTXYE,SUM(MYRZXYBS) AS MYRZXYBS,SUM(MYRZFSE) AS MYRZFSE,SUM(MYRZYE) AS MYRZYE,SUM(MYRZYWBS) AS MYRZYWBS,SUM(XYZBS) AS XYZBS,SUM(XYZFSE) AS XYZFSE,SUM(XYZYE) AS XYZYE,SUM(BHBS) AS BHBS,SUM(BHFSE) AS BHFSE,SUM(BHYE) AS BHYE,SUM(CDHPBS) AS CDHPBS,SUM(CDHPFSE) AS CDHPFSE,SUM(CDHPYE) AS CDHPYE,SUM(GKSXBS) AS GKSXBS,SUM(GKSXFSE) AS GKSXFSE,SUM(BZHTBS) AS BZHTBS,SUM(BZFSE) AS BZFSE,SUM(BZYE) AS BZYE,SUM(DYHTBS) AS DYHTBS,SUM(DYFSE) AS DYFSE,SUM(DYYE) AS DYYE,SUM(ZYHTBS) AS ZYHTBS,SUM(ZYFSE) AS ZYFSE,SUM(ZYYE) AS ZYYE,SUM(DIANKUANBS) AS DIANKUANBS,SUM(DIANKUANFSE) AS DIANKUANFSE,SUM(DIANKUANYE) AS DIANKUANYE,SUM(BNQXYE) AS BNQXYE,SUM(BWQXYE) AS BWQXYE,MAX(DJJGDM) AS DJJGDM,MAX(SJJZRQ) AS SJJZRQ FROM (

SELECT A.DKKBM,ZZJGDM,CTE_JKRMC AS JKRMC,DKHTBS,0.00 AS DKFSE,0.00 AS DKYE,0 AS JJBS,0 AS BLBS,0.00 AS BLFSE,0.00 AS BLYE,0 AS PJTXBS,0.00 AS PJTXFSE,0.00 AS PJTXYE,0 AS MYRZXYBS,0.00 AS MYRZFSE,0.00 AS MYRZYE,0 AS MYRZYWBS,0 AS XYZBS,0.00 AS XYZFSE,0.00 AS XYZYE,0 AS BHBS,0.00 AS BHFSE,0.00 AS BHYE,0 AS CDHPBS,0.00 AS CDHPFSE,0.00 AS CDHPYE,0 AS GKSXBS,0.00 AS GKSXFSE,0 AS BZHTBS,0.00 AS BZFSE,0.00 AS BZYE,0 AS DYHTBS,0.00 AS DYFSE,0.00 AS DYYE,0 AS ZYHTBS,0.00 AS ZYFSE,0.00 AS ZYYE,0 AS DIANKUANBS,0.00 AS DIANKUANFSE,0.00 AS DIANKUANYE,0.00 AS BNQXYE,0.00 AS BWQXYE,p_REPORTINST AS DJJGDM,p_ENDDATE AS SJJZRQ FROM (
SELECT DKKBM,COUNT(1) AS DKHTBS FROM (
SELECT DKKBM,FOREIGNID,MAX(QY_HTXX.EXTEND2) AS EXTEND2 FROM QY_HTXX,QY_DKYW_JC,REPORTINSTSUBINFO WHERE QY_HTXX.FOREIGNID = QY_DKYW_JC.AUTOID AND INSTINFO = STRINSTCODE AND QY_HTXX.EXTEND2 <= p_ENDDATE AND strReportInstCode = p_REPORTINST AND XXJLCZLX = '1' AND QY_HTXX.RPTFEEDBACKTYPE = '2' GROUP BY DKKBM,FOREIGNID) TEMP WHERE NOT EXISTS(
SELECT * FROM QY_HTXX WHERE QY_HTXX.FOREIGNID = TEMP.FOREIGNID AND QY_HTXX.EXTEND2 = TEMP.EXTEND2 AND QY_HTXX.HTYXZT = '2') 
GROUP BY DKKBM) A 
LEFT JOIN CTE_JGXX ON A.DKKBM = CTE_JGXX.DKKBM
UNION 

SELECT B.DKKBM,ZZJGDM,CTE_JKRMC AS JKRMC,0 AS DKHTBS,DKFSE,DKYE,JJBS,0 AS BLBS,0.00 AS BLFSE,0.00 AS BLYE,0 AS PJTXBS,0.00 AS PJTXFSE,0.00 AS PJTXYE,0 AS MYRZXYBS,0.00 AS MYRZFSE,0.00 AS MYRZYE,0 AS MYRZYWBS,0 AS XYZBS,0.00 AS XYZFSE,0.00 AS XYZYE,0 AS BHBS,0.00 AS BHFSE,0.00 AS BHYE,0 AS CDHPBS,0.00 AS CDHPFSE,0.00 AS CDHPYE,0 AS GKSXBS,0.00 AS GKSXFSE,0 AS BZHTBS,0.00 AS BZFSE,0.00 AS BZYE,0 AS DYHTBS,0.00 AS DYFSE,0.00 AS DYYE,0 AS ZYHTBS,0.00 AS ZYFSE,0.00 AS ZYYE,0 AS DIANKUANBS,0.00 AS DIANKUANFSE,0.00 AS DIANKUANYE,0.00 AS BNQXYE,0.00 AS BWQXYE,p_REPORTINST AS DJJGDM,p_ENDDATE AS SJJZRQ FROM (
SELECT DKKBM,SUM(CAST(DKJJJE AS DECIMAL(17,2))) AS DKFSE,SUM(CAST(DKJJYE AS DECIMAL(17,2))) AS DKYE,COUNT(1) AS JJBS FROM (
SELECT FOREIGNID,DKJJJE,DKJJYE,JJBH FROM QY_JJXX WHERE EXISTS(
SELECT * FROM (SELECT FOREIGNID,JJBH,MAX(QY_JJXX.EXTEND2) AS EXTEND2 FROM QY_JJXX,QY_DKYW_JC,REPORTINSTSUBINFO WHERE QY_JJXX.FOREIGNID = QY_DKYW_JC.AUTOID AND INSTINFO = STRINSTCODE AND QY_JJXX.EXTEND2 <= p_ENDDATE AND strReportInstCode = p_REPORTINST AND XXJLCZLX = '1' AND QY_JJXX.RPTFEEDBACKTYPE = '2' GROUP BY FOREIGNID,JJBH) TEMP 
WHERE QY_JJXX.FOREIGNID = TEMP.FOREIGNID AND QY_JJXX.JJBH = TEMP.JJBH AND QY_JJXX.EXTEND2 = TEMP.EXTEND2 AND QY_JJXX.DKJJYE <> '0.00')) TEMP2,QY_DKYW_JC WHERE TEMP2.FOREIGNID = QY_DKYW_JC.AUTOID 
GROUP BY DKKBM) B 
LEFT JOIN CTE_JGXX ON B.DKKBM = CTE_JGXX.DKKBM
UNION

SELECT C.DKKBM,ZZJGDM,CTE_JKRMC AS JKRMC,0 AS DKHTBS,0.00 AS DKFSE,0.00 AS DKYE,0 AS JJBS,BLBS,BLFSE,BLYE,0 AS PJTXBS,0.00 AS PJTXFSE,0.00 AS PJTXYE,0 AS MYRZXYBS,0.00 AS MYRZFSE,0.00 AS MYRZYE,0 AS MYRZYWBS,0 AS XYZBS,0.00 AS XYZFSE,0.00 AS XYZYE,0 AS BHBS,0.00 AS BHFSE,0.00 AS BHYE,0 AS CDHPBS,0.00 AS CDHPFSE,0.00 AS CDHPYE,0 AS GKSXBS,0.00 AS GKSXFSE,0 AS BZHTBS,0.00 AS BZFSE,0.00 AS BZYE,0 AS DYHTBS,0.00 AS DYFSE,0.00 AS DYYE,0 AS ZYHTBS,0.00 AS ZYFSE,0.00 AS ZYYE,0 AS DIANKUANBS,0.00 AS DIANKUANFSE,0.00 AS DIANKUANYE,0.00 AS BNQXYE,0.00 AS BWQXYE,p_REPORTINST AS DJJGDM,p_ENDDATE AS SJJZRQ FROM (
SELECT DKKBM,COUNT(1) AS BLBS,SUM(CAST(XZJE AS DECIMAL(17,2))) AS BLFSE,SUM(CAST(XZYE AS DECIMAL(17,2))) AS BLYE FROM QY_BLXZXX WHERE EXISTS (
SELECT * FROM (SELECT FOREIGNID,MAX(QY_BLXZXX.EXTEND2) AS EXTEND2 FROM QY_BLXZXX,QY_BLYW_JC,REPORTINSTSUBINFO WHERE QY_BLXZXX.FOREIGNID = QY_BLYW_JC.AUTOID AND INSTINFO = STRINSTCODE AND QY_BLXZXX.EXTEND2 <= p_ENDDATE AND strReportInstCode = p_REPORTINST AND XXJLCZLX = '1' AND QY_BLXZXX.RPTFEEDBACKTYPE = '2' GROUP BY FOREIGNID) TEMP 
WHERE QY_BLXZXX.FOREIGNID = TEMP.FOREIGNID AND QY_BLXZXX.EXTEND2 = TEMP.EXTEND2 AND QY_BLXZXX.XZYE <> '0.00') 
GROUP BY DKKBM) C 
LEFT JOIN CTE_JGXX ON C.DKKBM = CTE_JGXX.DKKBM
UNION

SELECT D.DKKBM,ZZJGDM,CTE_JKRMC AS JKRMC,0 AS DKHTBS,0.00 AS DKFSE,0.00 AS DKYE,0 AS JJBS,0 AS BLBS,0.00 AS BLFSE,0.00 AS BLYE,PJTXBS,PJTXFSE,PJTXYE,0 AS MYRZXYBS,0.00 AS MYRZFSE,0.00 AS MYRZYE,0 AS MYRZYWBS,0 AS XYZBS,0.00 AS XYZFSE,0.00 AS XYZYE,0 AS BHBS,0.00 AS BHFSE,0.00 AS BHYE,0 AS CDHPBS,0.00 AS CDHPFSE,0.00 AS CDHPYE,0 AS GKSXBS,0.00 AS GKSXFSE,0 AS BZHTBS,0.00 AS BZFSE,0.00 AS BZYE,0 AS DYHTBS,0.00 AS DYFSE,0.00 AS DYYE,0 AS ZYHTBS,0.00 AS ZYFSE,0.00 AS ZYYE,0 AS DIANKUANBS,0.00 AS DIANKUANFSE,0.00 AS DIANKUANYE,0.00 AS BNQXYE,0.00 AS BWQXYE,p_REPORTINST AS DJJGDM,p_ENDDATE AS SJJZRQ FROM (
SELECT DKKBM,COUNT(1) AS PJTXBS,SUM(CAST(TXJE AS DECIMAL(17,2))) AS PJTXFSE,SUM(CAST(TXJE AS DECIMAL(17,2))) AS PJTXYE FROM QY_TXYWXX WHERE EXISTS (
SELECT * FROM (SELECT FOREIGNID,MAX(QY_TXYWXX.EXTEND2) AS EXTEND2 FROM QY_TXYWXX,QY_PJTX_JC,REPORTINSTSUBINFO WHERE QY_TXYWXX.FOREIGNID = QY_PJTX_JC.AUTOID AND INSTINFO = STRINSTCODE AND QY_TXYWXX.EXTEND2 <= p_ENDDATE AND strReportInstCode = p_REPORTINST AND XXJLCZLX = '1' AND QY_TXYWXX.RPTFEEDBACKTYPE = '2' GROUP BY FOREIGNID) TEMP 
WHERE QY_TXYWXX.FOREIGNID = TEMP.FOREIGNID AND QY_TXYWXX.EXTEND2 = TEMP.EXTEND2 AND QY_TXYWXX.PJZT = '1') 
GROUP BY DKKBM) D 
LEFT JOIN CTE_JGXX ON D.DKKBM = CTE_JGXX.DKKBM
UNION

SELECT E.DKKBM,ZZJGDM,CTE_JKRMC AS JKRMC,0 AS DKHTBS,0.00 AS DKFSE,0.00 AS DKYE,0 AS JJBS,0 AS BLBS,0.00 AS BLFSE,0.00 AS BLYE,0 AS PJTXBS,0.00 AS PJTXFSE,0.00 AS PJTXYE,MYRZXYBS,0.00 AS MYRZFSE,0.00 AS MYRZYE,0 AS MYRZYWBS,0 AS XYZBS,0.00 AS XYZFSE,0.00 AS XYZYE,0 AS BHBS,0.00 AS BHFSE,0.00 AS BHYE,0 AS CDHPBS,0.00 AS CDHPFSE,0.00 AS CDHPYE,0 AS GKSXBS,0.00 AS GKSXFSE,0 AS BZHTBS,0.00 AS BZFSE,0.00 AS BZYE,0 AS DYHTBS,0.00 AS DYFSE,0.00 AS DYYE,0 AS ZYHTBS,0.00 AS ZYFSE,0.00 AS ZYYE,0 AS DIANKUANBS,0.00 AS DIANKUANFSE,0.00 AS DIANKUANYE,0.00 AS BNQXYE,0.00 AS BWQXYE,p_REPORTINST AS DJJGDM,p_ENDDATE AS SJJZRQ FROM (
SELECT DKKBM,COUNT(1) AS MYRZXYBS FROM (
SELECT DKKBM,FOREIGNID,MAX(QY_RZXYXX.EXTEND2) AS EXTEND2 FROM QY_RZXYXX,QY_MYRZ_JC,REPORTINSTSUBINFO WHERE QY_RZXYXX.FOREIGNID = QY_MYRZ_JC.AUTOID AND INSTINFO = STRINSTCODE AND QY_RZXYXX.EXTEND2 <= p_ENDDATE AND strReportInstCode = p_REPORTINST AND XXJLCZLX = '1' AND QY_RZXYXX.RPTFEEDBACKTYPE = '2' GROUP BY DKKBM,FOREIGNID) TEMP WHERE NOT EXISTS(
SELECT * FROM QY_RZXYXX WHERE QY_RZXYXX.FOREIGNID = TEMP.FOREIGNID AND QY_RZXYXX.EXTEND2 = TEMP.EXTEND2 AND QY_RZXYXX.XYYXZT = '2') 
GROUP BY DKKBM) E 
LEFT JOIN CTE_JGXX ON E.DKKBM = CTE_JGXX.DKKBM
UNION

SELECT F.DKKBM,ZZJGDM,CTE_JKRMC AS JKRMC,0 AS DKHTBS,0.00 AS DKFSE,0.00 AS DKYE,0 AS JJBS,0 AS BLBS,0.00 AS BLFSE,0.00 AS BLYE,0 AS PJTXBS,0.00 AS PJTXFSE,0.00 AS PJTXYE,0 AS MYRZXYBS,MYRZFSE,MYRZYE,MYRZYWBS,0 AS XYZBS,0.00 AS XYZFSE,0.00 AS XYZYE,0 AS BHBS,0.00 AS BHFSE,0.00 AS BHYE,0 AS CDHPBS,0.00 AS CDHPFSE,0.00 AS CDHPYE,0 AS GKSXBS,0.00 AS GKSXFSE,0 AS BZHTBS,0.00 AS BZFSE,0.00 AS BZYE,0 AS DYHTBS,0.00 AS DYFSE,0.00 AS DYYE,0 AS ZYHTBS,0.00 AS ZYFSE,0.00 AS ZYYE,0 AS DIANKUANBS,0.00 AS DIANKUANFSE,0.00 AS DIANKUANYE,0.00 AS BNQXYE,0.00 AS BWQXYE,p_REPORTINST AS DJJGDM,p_ENDDATE AS SJJZRQ FROM (
SELECT DKKBM,SUM(CAST(RZJE AS DECIMAL(17,2))) AS MYRZFSE,SUM(CAST(RZYE AS DECIMAL(17,2))) AS MYRZYE,COUNT(1) AS MYRZYWBS FROM (
SELECT FOREIGNID,RZJE,RZYE,RZYWBH FROM QY_RZYWXX WHERE EXISTS(
SELECT * FROM (SELECT FOREIGNID,RZYWBH,MAX(QY_RZYWXX.EXTEND2) AS EXTEND2 FROM QY_RZYWXX,QY_MYRZ_JC,REPORTINSTSUBINFO WHERE QY_RZYWXX.FOREIGNID = QY_MYRZ_JC.AUTOID AND INSTINFO = STRINSTCODE AND QY_RZYWXX.EXTEND2 <= p_ENDDATE AND strReportInstCode = p_REPORTINST AND XXJLCZLX = '1' AND QY_RZYWXX.RPTFEEDBACKTYPE = '2' GROUP BY FOREIGNID,RZYWBH) TEMP 
WHERE QY_RZYWXX.FOREIGNID = TEMP.FOREIGNID AND QY_RZYWXX.RZYWBH = TEMP.RZYWBH AND QY_RZYWXX.EXTEND2 = TEMP.EXTEND2 AND QY_RZYWXX.RZYE <> '0.00')) TEMP2,QY_MYRZ_JC 
WHERE TEMP2.FOREIGNID = QY_MYRZ_JC.AUTOID 
GROUP BY DKKBM) F 
LEFT JOIN CTE_JGXX ON F.DKKBM = CTE_JGXX.DKKBM
UNION

SELECT G.DKKBM,ZZJGDM,CTE_JKRMC AS JKRMC,0 AS DKHTBS,0.00 AS DKFSE,0.00 AS DKYE,0 AS JJBS,0 AS BLBS,0.00 AS BLFSE,0.00 AS BLYE,0 AS PJTXBS,0.00 AS PJTXFSE,0.00 AS PJTXYE,0 AS MYRZXYBS,0.00 AS MYRZFSE,0.00 AS MYRZYE,0 AS MYRZYWBS,XYZBS,XYZFSE,XYZYE,0 AS BHBS,0.00 AS BHFSE,0.00 AS BHYE,0 AS CDHPBS,0.00 AS CDHPFSE,0.00 AS CDHPYE,0 AS GKSXBS,0.00 AS GKSXFSE,0 AS BZHTBS,0.00 AS BZFSE,0.00 AS BZYE,0 AS DYHTBS,0.00 AS DYFSE,0.00 AS DYYE,0 AS ZYHTBS,0.00 AS ZYFSE,0.00 AS ZYYE,0 AS DIANKUANBS,0.00 AS DIANKUANFSE,0.00 AS DIANKUANYE,0.00 AS BNQXYE,0.00 AS BWQXYE,p_REPORTINST AS DJJGDM,p_ENDDATE AS SJJZRQ FROM (
SELECT DKKBM,COUNT(1) AS XYZBS,SUM(CAST(KZJE AS DECIMAL(17,2))) AS XYZFSE,SUM(CAST(XYZYE AS DECIMAL(17,2))) AS XYZYE FROM QY_XYZYWXX WHERE EXISTS (
SELECT * FROM (SELECT FOREIGNID,MAX(QY_XYZYWXX.EXTEND2) AS EXTEND2 FROM QY_XYZYWXX,QY_XYZYW_JC,REPORTINSTSUBINFO WHERE QY_XYZYWXX.FOREIGNID = QY_XYZYW_JC.AUTOID AND INSTINFO = STRINSTCODE AND QY_XYZYWXX.EXTEND2 <= p_ENDDATE AND strReportInstCode = p_REPORTINST AND XXJLCZLX = '1' AND QY_XYZYWXX.RPTFEEDBACKTYPE = '2' GROUP BY FOREIGNID) TEMP 
WHERE QY_XYZYWXX.FOREIGNID = TEMP.FOREIGNID AND QY_XYZYWXX.EXTEND2 = TEMP.EXTEND2 AND QY_XYZYWXX.XYZZT = '1') 
GROUP BY DKKBM) G 
LEFT JOIN CTE_JGXX ON G.DKKBM = CTE_JGXX.DKKBM
UNION

SELECT H.DKKBM,ZZJGDM,CTE_JKRMC AS JKRMC,0 AS DKHTBS,0.00 AS DKFSE,0.00 AS DKYE,0 AS JJBS,0 AS BLBS,0.00 AS BLFSE,0.00 AS BLYE,0 AS PJTXBS,0.00 AS PJTXFSE,0.00 AS PJTXYE,0 AS MYRZXYBS,0.00 AS MYRZFSE,0.00 AS MYRZYE,0 AS MYRZYWBS,0 AS XYZBS,0.00 AS XYZFSE,0.00 AS XYZYE,BHBS,BHFSE,BHYE,0 AS CDHPBS,0.00 AS CDHPFSE,0.00 AS CDHPYE,0 AS GKSXBS,0.00 AS GKSXFSE,0 AS BZHTBS,0.00 AS BZFSE,0.00 AS BZYE,0 AS DYHTBS,0.00 AS DYFSE,0.00 AS DYYE,0 AS ZYHTBS,0.00 AS ZYFSE,0.00 AS ZYYE,0 AS DIANKUANBS,0.00 AS DIANKUANFSE,0.00 AS DIANKUANYE,0.00 AS BNQXYE,0.00 AS BWQXYE,p_REPORTINST AS DJJGDM,p_ENDDATE AS SJJZRQ FROM (
SELECT DKKBM,COUNT(1) AS BHBS,SUM(CAST(BHJE AS DECIMAL(17,2))) AS BHFSE,SUM(CAST(BHYE AS DECIMAL(17,2))) AS BHYE FROM QY_BHYWXX WHERE EXISTS (
SELECT * FROM (SELECT FOREIGNID,MAX(QY_BHYWXX.EXTEND2) AS EXTEND2 FROM QY_BHYWXX,QY_BHYW_JC,REPORTINSTSUBINFO WHERE QY_BHYWXX.FOREIGNID = QY_BHYW_JC.AUTOID AND INSTINFO = STRINSTCODE AND QY_BHYWXX.EXTEND2 <= p_ENDDATE AND strReportInstCode = p_REPORTINST AND XXJLCZLX = '1' AND QY_BHYWXX.RPTFEEDBACKTYPE = '2' GROUP BY FOREIGNID) TEMP 
WHERE QY_BHYWXX.FOREIGNID = TEMP.FOREIGNID AND QY_BHYWXX.EXTEND2 = TEMP.EXTEND2 AND QY_BHYWXX.BHZT = '1') 
GROUP BY DKKBM) H 
LEFT JOIN CTE_JGXX ON H.DKKBM = CTE_JGXX.DKKBM
UNION

SELECT I.DKKBM,ZZJGDM,CTE_JKRMC AS JKRMC,0 AS DKHTBS,0.00 AS DKFSE,0.00 AS DKYE,0 AS JJBS,0 AS BLBS,0.00 AS BLFSE,0.00 AS BLYE,0 AS PJTXBS,0.00 AS PJTXFSE,0.00 AS PJTXYE,0 AS MYRZXYBS,0.00 AS MYRZFSE,0.00 AS MYRZYE,0 AS MYRZYWBS,0 AS XYZBS,0.00 AS XYZFSE,0.00 AS XYZYE,0 AS BHBS,0.00 AS BHFSE,0.00 AS BHYE,CDHPBS,CDHPFSE,CDHPYE,0 AS GKSXBS,0.00 AS GKSXFSE,0 AS BZHTBS,0.00 AS BZFSE,0.00 AS BZYE,0 AS DYHTBS,0.00 AS DYFSE,0.00 AS DYYE,0 AS ZYHTBS,0.00 AS ZYFSE,0.00 AS ZYYE,0 AS DIANKUANBS,0.00 AS DIANKUANFSE,0.00 AS DIANKUANYE,0.00 AS BNQXYE,0.00 AS BWQXYE,p_REPORTINST AS DJJGDM,p_ENDDATE AS SJJZRQ FROM (
SELECT DKKBM,COUNT(1) AS CDHPBS,SUM(CAST(HPJE AS DECIMAL(17,2))) AS CDHPFSE,SUM(CAST(HPJE AS DECIMAL(17,2))) AS CDHPYE FROM QY_HPYWXX WHERE EXISTS (
SELECT * FROM (SELECT FOREIGNID,MAX(QY_HPYWXX.EXTEND2) AS EXTEND2 FROM QY_HPYWXX,QY_YHCDHP_JC,REPORTINSTSUBINFO WHERE QY_HPYWXX.FOREIGNID = QY_YHCDHP_JC.AUTOID AND INSTINFO = STRINSTCODE AND QY_HPYWXX.EXTEND2 <= p_ENDDATE AND strReportInstCode = p_REPORTINST AND XXJLCZLX = '1' AND QY_HPYWXX.RPTFEEDBACKTYPE = '2' GROUP BY FOREIGNID) TEMP 
WHERE QY_HPYWXX.FOREIGNID = TEMP.FOREIGNID AND QY_HPYWXX.EXTEND2 = TEMP.EXTEND2 AND QY_HPYWXX.HPZT = '1') 
GROUP BY DKKBM) I 
LEFT JOIN CTE_JGXX ON I.DKKBM = CTE_JGXX.DKKBM
UNION

SELECT J.DKKBM,ZZJGDM,CTE_JKRMC AS JKRMC,0 AS DKHTBS,0.00 AS DKFSE,0.00 AS DKYE,0 AS JJBS,0 AS BLBS,0.00 AS BLFSE,0.00 AS BLYE,0 AS PJTXBS,0.00 AS PJTXFSE,0.00 AS PJTXYE,0 AS MYRZXYBS,0.00 AS MYRZFSE,0.00 AS MYRZYE,0 AS MYRZYWBS,0 AS XYZBS,0.00 AS XYZFSE,0.00 AS XYZYE,0 AS BHBS,0.00 AS BHFSE,0.00 AS BHYE,0 AS CDHPBS,0.00 AS CDHPFSE,0.00 AS CDHPYE,GKSXBS,GKSXFSE,0 AS BZHTBS,0.00 AS BZFSE,0.00 AS BZYE,0 AS DYHTBS,0.00 AS DYFSE,0.00 AS DYYE,0 AS ZYHTBS,0.00 AS ZYFSE,0.00 AS ZYYE,0 AS DIANKUANBS,0.00 AS DIANKUANFSE,0.00 AS DIANKUANYE,0.00 AS BNQXYE,0.00 AS BWQXYE,p_REPORTINST AS DJJGDM,p_ENDDATE AS SJJZRQ FROM (
SELECT DKKBM,COUNT(1) AS GKSXBS,SUM(CAST(SXED AS DECIMAL(17,2))) AS GKSXFSE FROM QY_SXYWXX WHERE EXISTS (
SELECT * FROM (SELECT FOREIGNID,MAX(QY_SXYWXX.EXTEND2) AS EXTEND2 FROM QY_SXYWXX,QY_GKSX_JC,REPORTINSTSUBINFO WHERE QY_SXYWXX.FOREIGNID = QY_GKSX_JC.AUTOID AND INSTINFO = STRINSTCODE AND QY_SXYWXX.EXTEND2 <= p_ENDDATE AND strReportInstCode = p_REPORTINST AND XXJLCZLX = '1' AND QY_SXYWXX.RPTFEEDBACKTYPE = '2' GROUP BY FOREIGNID) TEMP 
WHERE QY_SXYWXX.FOREIGNID = TEMP.FOREIGNID AND QY_SXYWXX.EXTEND2 = TEMP.EXTEND2 AND QY_SXYWXX.SXEDZXSXRQ > p_ENDDATE AND QY_SXYWXX.SXZZRQ > p_ENDDATE) 
GROUP BY DKKBM) J 
LEFT JOIN CTE_JGXX ON J.DKKBM = CTE_JGXX.DKKBM
UNION

SELECT K.BZRDDKKBM AS DKKBM,ZZJGDM,BZRMC AS JKRMC,0 AS DKHTBS,0.00 AS DKFSE,0.00 AS DKYE,0 AS JJBS,0 AS BLBS,0.00 AS BLFSE,0.00 AS BLYE,0 AS PJTXBS,0.00 AS PJTXFSE,0.00 AS PJTXYE,0 AS MYRZXYBS,0.00 AS MYRZFSE,0.00 AS MYRZYE,0 AS MYRZYWBS,0 AS XYZBS,0.00 AS XYZFSE,0.00 AS XYZYE,0 AS BHBS,0.00 AS BHFSE,0.00 AS BHYE,0 AS CDHPBS,0.00 AS CDHPFSE,0.00 AS CDHPYE,0 AS GKSXBS,0.00 AS GKSXFSE,BZHTBS,BZFSE,BZYE,0 AS DYHTBS,0.00 AS DYFSE,0.00 AS DYYE,0 AS ZYHTBS,0.00 AS ZYFSE,0.00 AS ZYYE,0 AS DIANKUANBS,0.00 AS DIANKUANFSE,0.00 AS DIANKUANYE,0.00 AS BNQXYE,0.00 AS BWQXYE,p_REPORTINST AS DJJGDM,p_ENDDATE AS SJJZRQ FROM (
SELECT BZRDDKKBM,MAX(BZRMC) AS BZRMC,COUNT(1) AS BZHTBS,SUM(CAST(BZJE AS DECIMAL(17,2))) AS BZFSE,SUM(CAST(BZJE AS DECIMAL(17,2))) AS BZYE FROM (
SELECT BZRDDKKBM,MAX(BZRMC) AS BZRMC,MAX(BZJE) AS BZJE FROM QY_DBHTXX WHERE EXISTS (
SELECT * FROM (SELECT BZRDDKKBM,BZHTBH,MAX(QY_DBHTXX.EXTEND2) AS EXTEND2 FROM QY_DBHTXX,QY_DBXX_JC,REPORTINSTSUBINFO WHERE QY_DBHTXX.FOREIGNID = QY_DBXX_JC.AUTOID AND INSTINFO = STRINSTCODE AND QY_DBHTXX.EXTEND2 <= p_ENDDATE AND strReportInstCode = p_REPORTINST AND XXJLCZLX = '1' AND QY_DBHTXX.RPTFEEDBACKTYPE = '2' AND QY_DBHTXX.HTYXZT = '1' GROUP BY BZRDDKKBM,BZHTBH) TEMP 
WHERE QY_DBHTXX.BZRDDKKBM = TEMP.BZRDDKKBM AND QY_DBHTXX.BZHTBH = TEMP.BZHTBH AND QY_DBHTXX.EXTEND2 = TEMP.EXTEND2) GROUP BY BZRDDKKBM,BZHTBH) TEMP2
GROUP BY BZRDDKKBM) K 
LEFT JOIN CTE_JGXX ON K.BZRDDKKBM = CTE_JGXX.DKKBM
UNION

SELECT L.DYRDKKBM AS DKKBM,ZZJGDM,DYRMC AS JKRMC,0 AS DKHTBS,0.00 AS DKFSE,0.00 AS DKYE,0 AS JJBS,0 AS BLBS,0.00 AS BLFSE,0.00 AS BLYE,0 AS PJTXBS,0.00 AS PJTXFSE,0.00 AS PJTXYE,0 AS MYRZXYBS,0.00 AS MYRZFSE,0.00 AS MYRZYE,0 AS MYRZYWBS,0 AS XYZBS,0.00 AS XYZFSE,0.00 AS XYZYE,0 AS BHBS,0.00 AS BHFSE,0.00 AS BHYE,0 AS CDHPBS,0.00 AS CDHPFSE,0.00 AS CDHPYE,0 AS GKSXBS,0.00 AS GKSXFSE,0 AS BZHTBS,0.00 AS BZFSE,0.00 AS BZYE,DYHTBS,DYFSE,DYYE,0 AS ZYHTBS,0.00 AS ZYFSE,0.00 AS ZYYE,0 AS DIANKUANBS,0.00 AS DIANKUANFSE,0.00 AS DIANKUANYE,0.00 AS BNQXYE,0.00 AS BWQXYE,p_REPORTINST AS DJJGDM,p_ENDDATE AS SJJZRQ FROM (
SELECT DYRDKKBM,MAX(DYRMC) AS DYRMC,COUNT(1) AS DYHTBS,SUM(CAST(DYJE AS DECIMAL(17,2))) AS DYFSE,SUM(CAST(DYJE AS DECIMAL(17,2))) AS DYYE FROM (
SELECT DYRDKKBM,MAX(DYRMC) AS DYRMC,SUM(CAST(DYJE AS DECIMAL(17,2))) AS DYJE FROM (
SELECT DYRDKKBM,MAX(DYRMC) AS DYRMC,DYHTBM,MAX(DYJE) AS DYJE FROM QY_DYHTXX WHERE EXISTS (
SELECT * FROM (SELECT DYRDKKBM,DYHTBM,DYXH,MAX(QY_DYHTXX.EXTEND2) AS EXTEND2 FROM QY_DYHTXX,QY_DBXX_JC,REPORTINSTSUBINFO WHERE QY_DYHTXX.FOREIGNID = QY_DBXX_JC.AUTOID AND INSTINFO = STRINSTCODE AND QY_DYHTXX.EXTEND2 <= p_ENDDATE AND strReportInstCode = p_REPORTINST AND XXJLCZLX = '1' AND QY_DYHTXX.RPTFEEDBACKTYPE = '2' AND QY_DYHTXX.HTYXZT = '1' GROUP BY DYRDKKBM,DYHTBM,DYXH) TEMP 
WHERE QY_DYHTXX.DYRDKKBM = TEMP.DYRDKKBM AND QY_DYHTXX.DYHTBM = TEMP.DYHTBM AND QY_DYHTXX.DYXH = TEMP.DYXH AND QY_DYHTXX.EXTEND2 = TEMP.EXTEND2) GROUP BY DYRDKKBM,DYHTBM,DYXH) TEMP2
GROUP BY DYRDKKBM,DYHTBM) TEMP3 
GROUP BY DYRDKKBM) L 
LEFT JOIN CTE_JGXX ON L.DYRDKKBM = CTE_JGXX.DKKBM
UNION 

SELECT M.CZRDDKKBM AS DKKBM,ZZJGDM,CZRMC AS JKRMC,0 AS DKHTBS,0.00 AS DKFSE,0.00 AS DKYE,0 AS JJBS,0 AS BLBS,0.00 AS BLFSE,0.00 AS BLYE,0 AS PJTXBS,0.00 AS PJTXFSE,0.00 AS PJTXYE,0 AS MYRZXYBS,0.00 AS MYRZFSE,0.00 AS MYRZYE,0 AS MYRZYWBS,0 AS XYZBS,0.00 AS XYZFSE,0.00 AS XYZYE,0 AS BHBS,0.00 AS BHFSE,0.00 AS BHYE,0 AS CDHPBS,0.00 AS CDHPFSE,0.00 AS CDHPYE,0 AS GKSXBS,0.00 AS GKSXFSE,0 AS BZHTBS,0.00 AS BZFSE,0.00 AS BZYE,0 AS DYHTBS,0.00 AS DYFSE,0.00 AS DYYE,ZYHTBS,ZYFSE,ZYYE,0 AS DIANKUANBS,0.00 AS DIANKUANFSE,0.00 AS DIANKUANYE,0.00 AS BNQXYE,0.00 AS BWQXYE,p_REPORTINST AS DJJGDM,p_ENDDATE AS SJJZRQ FROM (
SELECT CZRDDKKBM,MAX(CZRMC) AS CZRMC,COUNT(1) AS ZYHTBS,SUM(CAST(ZYJE AS DECIMAL(17,2))) AS ZYFSE,SUM(CAST(ZYJE AS DECIMAL(17,2))) AS ZYYE FROM (
SELECT CZRDDKKBM,MAX(CZRMC) AS CZRMC,SUM(CAST(ZYJE AS DECIMAL(17,2))) AS ZYJE FROM (
SELECT CZRDDKKBM,MAX(CZRMC) AS CZRMC,ZYHTBH,MAX(ZYJE) AS ZYJE FROM QY_ZYHTXX WHERE EXISTS (
SELECT * FROM (SELECT CZRDDKKBM,ZYHTBH,ZYXH,MAX(QY_ZYHTXX.EXTEND2) AS EXTEND2 FROM QY_ZYHTXX,QY_DBXX_JC,REPORTINSTSUBINFO WHERE QY_ZYHTXX.FOREIGNID = QY_DBXX_JC.AUTOID AND INSTINFO = STRINSTCODE AND QY_ZYHTXX.EXTEND2 <= p_ENDDATE AND strReportInstCode = p_REPORTINST AND XXJLCZLX = '1' AND QY_ZYHTXX.RPTFEEDBACKTYPE = '2' AND QY_ZYHTXX.HTYXZT = '1' GROUP BY CZRDDKKBM,ZYHTBH,ZYXH) TEMP 
WHERE QY_ZYHTXX.CZRDDKKBM = TEMP.CZRDDKKBM AND QY_ZYHTXX.ZYHTBH = TEMP.ZYHTBH AND QY_ZYHTXX.ZYXH = TEMP.ZYXH AND QY_ZYHTXX.EXTEND2 = TEMP.EXTEND2) GROUP BY CZRDDKKBM,ZYHTBH,ZYXH) TEMP2 
GROUP BY CZRDDKKBM,ZYHTBH) TEMP3
GROUP BY CZRDDKKBM) M 
LEFT JOIN CTE_JGXX ON M.CZRDDKKBM = CTE_JGXX.DKKBM
UNION

SELECT N.DKKBM AS DKKBM,ZZJGDM,CTE_JKRMC AS JKRMC,0 AS DKHTBS,0.00 AS DKFSE,0.00 AS DKYE,0 AS JJBS,0 AS BLBS,0.00 AS BLFSE,0.00 AS BLYE,0 AS PJTXBS,0.00 AS PJTXFSE,0.00 AS PJTXYE,0 AS MYRZXYBS,0.00 AS MYRZFSE,0.00 AS MYRZYE,0 AS MYRZYWBS,0 AS XYZBS,0.00 AS XYZFSE,0.00 AS XYZYE,0 AS BHBS,0.00 AS BHFSE,0.00 AS BHYE,0 AS CDHPBS,0.00 AS CDHPFSE,0.00 AS CDHPYE,0 AS GKSXBS,0.00 AS GKSXFSE,0 AS BZHTBS,0.00 AS BZFSE,0.00 AS BZYE,0 AS DYHTBS,0.00 AS DYFSE,0.00 AS DYYE,0 AS ZYHTBS,0.00 AS ZYFSE,0.00 AS ZYYE,DIANKUANBS,DIANKUANFSE,DIANKUANYE,0.00 AS BNQXYE,0.00 AS BWQXYE,p_REPORTINST AS DJJGDM,p_ENDDATE AS SJJZRQ FROM (
SELECT DKKBM,COUNT(1) AS DIANKUANBS,SUM(CAST(DKJE AS DECIMAL(17,2))) AS DIANKUANFSE,SUM(CAST(DKYE AS DECIMAL(17,2))) AS DIANKUANYE FROM QY_DKYWXX WHERE EXISTS (
SELECT * FROM (SELECT FOREIGNID,MAX(QY_DKYWXX.EXTEND2) AS EXTEND2 FROM QY_DKYWXX,QY_DKXX_JC,REPORTINSTSUBINFO WHERE QY_DKYWXX.FOREIGNID = QY_DKXX_JC.AUTOID AND INSTINFO = STRINSTCODE AND QY_DKYWXX.EXTEND2 <= p_ENDDATE AND strReportInstCode = p_REPORTINST AND XXJLCZLX = '1' AND QY_DKYWXX.RPTFEEDBACKTYPE = '2' GROUP BY FOREIGNID) TEMP 
WHERE QY_DKYWXX.FOREIGNID = TEMP.FOREIGNID AND QY_DKYWXX.EXTEND2 = TEMP.EXTEND2 AND QY_DKYWXX.DKYE <> '0.00') 
GROUP BY DKKBM) N 
LEFT JOIN CTE_JGXX ON N.DKKBM = CTE_JGXX.DKKBM
UNION

SELECT O.DKKBM AS DKKBM,ZZJGDM,CTE_JKRMC AS JKRMC,0 AS DKHTBS,0.00 AS DKFSE,0.00 AS DKYE,0 AS JJBS,0 AS BLBS,0.00 AS BLFSE,0.00 AS BLYE,0 AS PJTXBS,0.00 AS PJTXFSE,0.00 AS PJTXYE,0 AS MYRZXYBS,0.00 AS MYRZFSE,0.00 AS MYRZYE,0 AS MYRZYWBS,0 AS XYZBS,0.00 AS XYZFSE,0.00 AS XYZYE,0 AS BHBS,0.00 AS BHFSE,0.00 AS BHYE,0 AS CDHPBS,0.00 AS CDHPFSE,0.00 AS CDHPYE,0 AS GKSXBS,0.00 AS GKSXFSE,0 AS BZHTBS,0.00 AS BZFSE,0.00 AS BZYE,0 AS DYHTBS,0.00 AS DYFSE,0.00 AS DYYE,0 AS ZYHTBS,0.00 AS ZYFSE,0.00 AS ZYYE,0 AS DIANKUANBS,0.00 AS DIANKUANFSE,0.00 AS DIANKUANYE,BNQXYE,0.00 AS BWQXYE,p_REPORTINST AS DJJGDM,p_ENDDATE AS SJJZRQ FROM (
SELECT DKKBM,SUM(CAST(QXYE AS DECIMAL(17,2))) AS BNQXYE FROM (
SELECT FOREIGNID,QXYE FROM QY_QXYWXX WHERE EXISTS(
SELECT * FROM (SELECT FOREIGNID,MAX(QY_QXYWXX.EXTEND2) AS EXTEND2 FROM QY_QXYWXX,QY_QXXX_JC,REPORTINSTSUBINFO WHERE QY_QXYWXX.FOREIGNID = QY_QXXX_JC.AUTOID AND INSTINFO = STRINSTCODE AND QY_QXYWXX.EXTEND2 <= p_ENDDATE AND strReportInstCode = p_REPORTINST AND XXJLCZLX = '1' AND QY_QXYWXX.RPTFEEDBACKTYPE = '2' GROUP BY FOREIGNID) TEMP 
WHERE QY_QXYWXX.FOREIGNID = TEMP.FOREIGNID AND QY_QXYWXX.EXTEND2 = TEMP.EXTEND2 AND QY_QXYWXX.QXYE <> '0.00' AND QY_QXYWXX.QXLX = '1')) TEMP2,QY_QXXX_JC WHERE TEMP2.FOREIGNID = QY_QXXX_JC.AUTOID 
GROUP BY DKKBM) O 
LEFT JOIN CTE_JGXX ON O.DKKBM = CTE_JGXX.DKKBM
UNION

SELECT P.DKKBM AS DKKBM,ZZJGDM,CTE_JKRMC AS JKRMC,0 AS DKHTBS,0.00 AS DKFSE,0.00 AS DKYE,0 AS JJBS,0 AS BLBS,0.00 AS BLFSE,0.00 AS BLYE,0 AS PJTXBS,0.00 AS PJTXFSE,0.00 AS PJTXYE,0 AS MYRZXYBS,0.00 AS MYRZFSE,0.00 AS MYRZYE,0 AS MYRZYWBS,0 AS XYZBS,0.00 AS XYZFSE,0.00 AS XYZYE,0 AS BHBS,0.00 AS BHFSE,0.00 AS BHYE,0 AS CDHPBS,0.00 AS CDHPFSE,0.00 AS CDHPYE,0 AS GKSXBS,0.00 AS GKSXFSE,0 AS BZHTBS,0.00 AS BZFSE,0.00 AS BZYE,0 AS DYHTBS,0.00 AS DYFSE,0.00 AS DYYE,0 AS ZYHTBS,0.00 AS ZYFSE,0.00 AS ZYYE,0 AS DIANKUANBS,0.00 AS DIANKUANFSE,0.00 AS DIANKUANYE,0.00 AS BNQXYE,BWQXYE,p_REPORTINST AS DJJGDM,p_ENDDATE AS SJJZRQ FROM (
SELECT DKKBM,SUM(CAST(QXYE AS DECIMAL(17,2))) AS BWQXYE FROM (
SELECT FOREIGNID,QXYE FROM QY_QXYWXX WHERE EXISTS(
SELECT * FROM (SELECT FOREIGNID,MAX(QY_QXYWXX.EXTEND2) AS EXTEND2 FROM QY_QXYWXX,QY_QXXX_JC,REPORTINSTSUBINFO WHERE QY_QXYWXX.FOREIGNID = QY_QXXX_JC.AUTOID AND INSTINFO = STRINSTCODE AND QY_QXYWXX.EXTEND2 <= p_ENDDATE AND strReportInstCode = p_REPORTINST AND XXJLCZLX = '1' AND QY_QXYWXX.RPTFEEDBACKTYPE = '2' GROUP BY FOREIGNID) TEMP 
WHERE QY_QXYWXX.FOREIGNID = TEMP.FOREIGNID AND QY_QXYWXX.EXTEND2 = TEMP.EXTEND2 AND QY_QXYWXX.QXYE <> '0.00' AND QY_QXYWXX.QXLX = '2')) TEMP2,QY_QXXX_JC WHERE TEMP2.FOREIGNID = QY_QXXX_JC.AUTOID 
GROUP BY DKKBM) P 
LEFT JOIN CTE_JGXX ON P.DKKBM = CTE_JGXX.DKKBM
UNION

SELECT ZJLX AS DKKBM,ZJHM AS ZZJGDM,MAX(BZRMC) AS JKRMC,0 AS DKHTBS,0.00 AS DKFSE,0.00 AS DKYE,0 AS JJBS,0 AS BLBS,0.00 AS BLFSE,0.00 AS BLYE,0 AS PJTXBS,0.00 AS PJTXFSE,0.00 AS PJTXYE,0 AS MYRZXYBS,0.00 AS MYRZFSE,0.00 AS MYRZYE,0 AS MYRZYWBS,0 AS XYZBS,0.00 AS XYZFSE,0.00 AS XYZYE,0 AS BHBS,0.00 AS BHFSE,0.00 AS BHYE,0 AS CDHPBS,0.00 AS CDHPFSE,0.00 AS CDHPYE,0 AS GKSXBS,0.00 AS GKSXFSE,COUNT(1) AS BZHTBS,SUM(CAST(BZJE AS DECIMAL(17,2))) AS BZFSE,SUM(CAST(BZJE AS DECIMAL(17,2))) AS BZYE,0 AS DYHTBS,0.00 AS DYFSE,0.00 AS DYYE,0 AS ZYHTBS,0.00 AS ZYFSE,0.00 AS ZYYE,0 AS DIANKUANBS,0.00 AS DIANKUANFSE,0.00 AS DIANKUANYE,0.00 AS BNQXYE,0.00 AS BWQXYE,p_REPORTINST AS DJJGDM,p_ENDDATE AS SJJZRQ FROM (
SELECT ZJLX,ZJHM,MAX(BZRMC) AS BZRMC,MAX(BZJE) AS BZJE FROM QY_ZRRBZHTXX WHERE EXISTS (
SELECT * FROM (SELECT ZJLX,ZJHM,BZHTBH,MAX(QY_ZRRBZHTXX.EXTEND2) AS EXTEND2 FROM QY_ZRRBZHTXX,QY_DBXX_JC,REPORTINSTSUBINFO WHERE QY_ZRRBZHTXX.FOREIGNID = QY_DBXX_JC.AUTOID AND INSTINFO = STRINSTCODE AND QY_ZRRBZHTXX.EXTEND2 <= p_ENDDATE AND strReportInstCode = p_REPORTINST AND XXJLCZLX = '1' AND QY_ZRRBZHTXX.RPTFEEDBACKTYPE = '2' AND QY_ZRRBZHTXX.HTYXZT = '1' GROUP BY ZJLX,ZJHM,BZHTBH) TEMP 
WHERE QY_ZRRBZHTXX.ZJLX = TEMP.ZJLX AND QY_ZRRBZHTXX.ZJHM = TEMP.ZJHM AND QY_ZRRBZHTXX.BZHTBH = TEMP.BZHTBH AND QY_ZRRBZHTXX.EXTEND2 = TEMP.EXTEND2) GROUP BY ZJLX,ZJHM,BZHTBH) TEMP2
GROUP BY ZJLX,ZJHM
UNION

SELECT ZJLX AS DKKBM,ZJHM AS ZZJGDM,MAX(DYRMC) AS JKRMC,0 AS DKHTBS,0.00 AS DKFSE,0.00 AS DKYE,0 AS JJBS,0 AS BLBS,0.00 AS BLFSE,0.00 AS BLYE,0 AS PJTXBS,0.00 AS PJTXFSE,0.00 AS PJTXYE,0 AS MYRZXYBS,0.00 AS MYRZFSE,0.00 AS MYRZYE,0 AS MYRZYWBS,0 AS XYZBS,0.00 AS XYZFSE,0.00 AS XYZYE,0 AS BHBS,0.00 AS BHFSE,0.00 AS BHYE,0 AS CDHPBS,0.00 AS CDHPFSE,0.00 AS CDHPYE,0 AS GKSXBS,0.00 AS GKSXFSE,0 AS BZHTBS,0.00 AS BZFSE,0.00 AS BZYE,COUNT(1) AS DYHTBS,SUM(DYJE) AS DYFSE,SUM(DYJE) AS DYYE,0 AS ZYHTBS,0.00 AS ZYFSE,0.00 AS ZYYE,0 AS DIANKUANBS,0.00 AS DIANKUANFSE,0.00 AS DIANKUANYE,0.00 AS BNQXYE,0.00 AS BWQXYE,p_REPORTINST AS DJJGDM,p_ENDDATE AS SJJZRQ FROM (
SELECT ZJLX,ZJHM,MAX(DYRMC) AS DYRMC,SUM(CAST(DYJE AS DECIMAL(17,2))) AS DYJE FROM (
SELECT ZJLX,ZJHM,MAX(DYRMC) AS DYRMC,DYHTBH,MAX(DYJE) AS DYJE FROM QY_ZRRDYHTXX WHERE EXISTS (
SELECT * FROM (SELECT ZJLX,ZJHM,DYHTBH,DYXH,MAX(QY_ZRRDYHTXX.EXTEND2) AS EXTEND2 FROM QY_ZRRDYHTXX,QY_DBXX_JC,REPORTINSTSUBINFO WHERE QY_ZRRDYHTXX.FOREIGNID = QY_DBXX_JC.AUTOID AND INSTINFO = STRINSTCODE AND QY_ZRRDYHTXX.EXTEND2 <= p_ENDDATE AND strReportInstCode = p_REPORTINST AND XXJLCZLX = '1' AND QY_ZRRDYHTXX.RPTFEEDBACKTYPE = '2' AND QY_ZRRDYHTXX.HTYXZT = '1' GROUP BY ZJLX,ZJHM,DYHTBH,DYXH) TEMP 
WHERE QY_ZRRDYHTXX.ZJLX = TEMP.ZJLX AND QY_ZRRDYHTXX.ZJHM = TEMP.ZJHM AND QY_ZRRDYHTXX.DYHTBH = TEMP.DYHTBH AND QY_ZRRDYHTXX.DYXH = TEMP.DYXH AND QY_ZRRDYHTXX.EXTEND2 = TEMP.EXTEND2) GROUP BY ZJLX,ZJHM,DYHTBH,DYXH) TEMP2 
GROUP BY ZJLX,ZJHM,DYHTBH) TEMP3
GROUP BY ZJLX,ZJHM
UNION

SELECT ZJLX AS DKKBM,ZJHM AS ZZJGDM,MAX(CZRMC) AS JKRMC,0 AS DKHTBS,0.00 AS DKFSE,0.00 AS DKYE,0 AS JJBS,0 AS BLBS,0.00 AS BLFSE,0.00 AS BLYE,0 AS PJTXBS,0.00 AS PJTXFSE,0.00 AS PJTXYE,0 AS MYRZXYBS,0.00 AS MYRZFSE,0.00 AS MYRZYE,0 AS MYRZYWBS,0 AS XYZBS,0.00 AS XYZFSE,0.00 AS XYZYE,0 AS BHBS,0.00 AS BHFSE,0.00 AS BHYE,0 AS CDHPBS,0.00 AS CDHPFSE,0.00 AS CDHPYE,0 AS GKSXBS,0.00 AS GKSXFSE,0 AS BZHTBS,0.00 AS BZFSE,0.00 AS BZYE,0 AS DYHTBS,0.00 AS DYFSE,0.00 AS DYYE,COUNT(1) AS ZYHTBS,SUM(ZYJE) AS ZYFSE,SUM(ZYJE) AS ZYYE,0 AS DIANKUANBS,0.00 AS DIANKUANFSE,0.00 AS DIANKUANYE,0.00 AS BNQXYE,0.00 AS BWQXYE,p_REPORTINST AS DJJGDM,p_ENDDATE AS SJJZRQ FROM (
SELECT ZJLX,ZJHM,MAX(CZRMC) AS CZRMC,SUM(CAST(ZYJE AS DECIMAL(17,2))) AS ZYJE FROM (
SELECT ZJLX,ZJHM,MAX(CZRMC) AS CZRMC,ZYHTBH,MAX(ZYJE) AS ZYJE FROM QY_ZRRZYHTXX WHERE EXISTS (
SELECT * FROM (SELECT ZJLX,ZJHM,ZYHTBH,ZYXH,MAX(QY_ZRRZYHTXX.EXTEND2) AS EXTEND2 FROM QY_ZRRZYHTXX,QY_DBXX_JC,REPORTINSTSUBINFO WHERE QY_ZRRZYHTXX.FOREIGNID = QY_DBXX_JC.AUTOID AND INSTINFO = STRINSTCODE AND QY_ZRRZYHTXX.EXTEND2 <= p_ENDDATE AND strReportInstCode = p_REPORTINST AND XXJLCZLX = '1' AND QY_ZRRZYHTXX.RPTFEEDBACKTYPE = '2' AND QY_ZRRZYHTXX.HTYXZT = '1' GROUP BY ZJLX,ZJHM,ZYHTBH,ZYXH) TEMP 
WHERE QY_ZRRZYHTXX.ZJLX = TEMP.ZJLX AND QY_ZRRZYHTXX.ZJHM = TEMP.ZJHM AND QY_ZRRZYHTXX.ZYHTBH = TEMP.ZYHTBH AND QY_ZRRZYHTXX.ZYXH = TEMP.ZYXH AND QY_ZRRZYHTXX.EXTEND2 = TEMP.EXTEND2) GROUP BY ZJLX,ZJHM,ZYHTBH,ZYXH) TEMP2 
GROUP BY ZJLX,ZJHM,ZYHTBH) TEMP3
GROUP BY ZJLX,ZJHM
) TEMPA
GROUP BY DKKBM,ZZJGDM) TEMPB;
END IF;
END PROC_EndsData_Check;