CREATE OR REPLACE PROCEDURE PROC_PENDSDATA_CHECK
(
	IN p_REPORTINST VARCHAR(50),
	IN p_ENDMONTH VARCHAR(6),
	IN FIRSTRESULT VARCHAR(10),
	IN PAGECOUNT VARCHAR(10)
)
  DYNAMIC RESULT SETS 1
  LANGUAGE SQL
BEGIN

DECLARE cur CURSOR WITH RETURN TO CALLER FOR 
SELECT JRJGDM,YWH,KHRQ,YWZLXF,YE,XM,ZJLX,ZJHM FROM GR_GRXX_JC WHERE EXISTS (
SELECT * FROM (SELECT YWH,MAX(JSYHKRQ) AS JSYHKRQ FROM GR_GRXX_JC,REPORTINSTSUBINFO
WHERE INSTINFO = STRINSTCODE AND strReportInstCode = p_REPORTINST AND SUBSTR(JSYHKRQ,1,6) <= p_ENDMONTH AND RPTFeedbackType = '2' GROUP BY YWH) TEMP 
WHERE GR_GRXX_JC.YWH = TEMP.YWH AND GR_GRXX_JC.JSYHKRQ = TEMP.JSYHKRQ AND GR_GRXX_JC.YE <> 0);

OPEN cur;
END