CREATE PROCEDURE [dbo].[PROC_PEndsData_Check] 
(
	@p_REPORTINST VARCHAR(50),
	@p_ENDMONTH VARCHAR(6),
	@FIRSTRESULT VARCHAR(10),
	@PAGECOUNT VARCHAR(10)
)
AS
BEGIN

SELECT JRJGDM,YWH,KHRQ,YWZLXF,YE,XM,ZJLX,ZJHM FROM GR_GRXX_JC WHERE EXISTS (
SELECT * FROM (SELECT YWH,MAX(JSYHKRQ) AS JSYHKRQ FROM GR_GRXX_JC,REPORTINSTSUBINFO
WHERE INSTINFO = STRINSTCODE AND strReportInstCode = @p_REPORTINST AND SUBSTRING(JSYHKRQ,1,6) <= @p_ENDMONTH AND RPTFeedbackType = '2' GROUP BY YWH) TEMP 
WHERE GR_GRXX_JC.YWH = TEMP.YWH AND GR_GRXX_JC.JSYHKRQ = TEMP.JSYHKRQ AND GR_GRXX_JC.YE <> 0)

END
