CREATE procedure [dbo].[Proc_Check_QY_02LRJLRFPB]
(
	@dtDate varchar(10),
	@strInstCode varchar(20)
)
as
if @dtDate='*****' and @strInstCode='*****'
SELECT  a.dtDate
	  , a.instInfo 
	  , b.autoID
      , b.BCLDZB
      , b.BTSR
      , b.BTSRBT9719
      , b.CWFY
      , b.DGDXSR
      , b.DXLYDLR
      , b.DYSY
      , b.GLFY
      , b.JLR
      , b.JYFY
      , b.KGFPDLR
      , b.KGTZZFPDLR
      , b.LRGHTZ
      , b.LRZR
      , b.NCWFPLR
      , b.QHSY
      , b.QT9691
      , b.QT9699
      , b.QT9907
      , b.QT9909
      , b.QT9911
      , b.QT9913
      , b.QTTZYS
      , b.QTYWLR
      , b.QTYYQN9731
      , b.QTZC
      , b.QTZCJZ9745
      , b.RPTCheckType
      , b.RPTFeedbackType
      , b.RPTSendType
      , b.SDS
      , b.SSGDSY
      , b.TQCBJJ
      , b.TQFDGYJ
      , b.TQFDYYGJ
      , b.TQQYFZJJ
      , b.TQRYYYGJ
      , b.TQZGJJJFLJJ
      , b.TZSY
      , b.WFPLR
      , b.WFPLR9793
      , b.WQRDTZSS
      , b.YFPTGGL
      , b.YFYXGGL
      , b.YYFY
      , b.YYGJBK
      , b.YYLR
      , b.YYWSR
      , b.YYWSRC9723
      , b.YYWSRC9727
      , b.YYWSRF9725
      , b.YYWSRFKJSR
      , b.YYWZC
      , b.YYWZCC9735
      , b.YYWZCFKZC
      , b.YYWZCJZZC
      , b.YYWZCZ9737
      , b.ZKYCR
      , b.ZYYWCB
      , b.ZYYWCB9687
      , b.ZYYWLR
      , b.ZYYWSJJFJ
      , b.ZYYWSR
      , b.ZYYWSR9677
      , b.ZYYWSR9679
      , b.ZYYWSRJE
      , b.ZZZBDPTGGL
      , b.extend1
      , b.extend2
      , b.extend3
      , b.extend4
      , b.extend5
      , b.FOREIGNID
  FROM QY_JKRCWBB_JC as a, QY_02LRJLRFPB as b
  WHERE  a.autoID=b.foreignid;
else
SELECT  a.dtDate
	  , a.instInfo 
	  , b.autoID
      , b.BCLDZB
      , b.BTSR
      , b.BTSRBT9719
      , b.CWFY
      , b.DGDXSR
      , b.DXLYDLR
      , b.DYSY
      , b.GLFY
      , b.JLR
      , b.JYFY
      , b.KGFPDLR
      , b.KGTZZFPDLR
      , b.LRGHTZ
      , b.LRZR
      , b.NCWFPLR
      , b.QHSY
      , b.QT9691
      , b.QT9699
      , b.QT9907
      , b.QT9909
      , b.QT9911
      , b.QT9913
      , b.QTTZYS
      , b.QTYWLR
      , b.QTYYQN9731
      , b.QTZC
      , b.QTZCJZ9745
      , b.RPTCheckType
      , b.RPTFeedbackType
      , b.RPTSendType
      , b.SDS
      , b.SSGDSY
      , b.TQCBJJ
      , b.TQFDGYJ
      , b.TQFDYYGJ
      , b.TQQYFZJJ
      , b.TQRYYYGJ
      , b.TQZGJJJFLJJ
      , b.TZSY
      , b.WFPLR
      , b.WFPLR9793
      , b.WQRDTZSS
      , b.YFPTGGL
      , b.YFYXGGL
      , b.YYFY
      , b.YYGJBK
      , b.YYLR
      , b.YYWSR
      , b.YYWSRC9723
      , b.YYWSRC9727
      , b.YYWSRF9725
      , b.YYWSRFKJSR
      , b.YYWZC
      , b.YYWZCC9735
      , b.YYWZCFKZC
      , b.YYWZCJZZC
      , b.YYWZCZ9737
      , b.ZKYCR
      , b.ZYYWCB
      , b.ZYYWCB9687
      , b.ZYYWLR
      , b.ZYYWSJJFJ
      , b.ZYYWSR
      , b.ZYYWSR9677
      , b.ZYYWSR9679
      , b.ZYYWSRJE
      , b.ZZZBDPTGGL
      , b.extend1
      , b.extend2
      , b.extend3
      , b.extend4
      , b.extend5
      , b.FOREIGNID
  FROM QY_JKRCWBB_JC as a, QY_02LRJLRFPB as b
  WHERE a.dtDate=@dtDate and a.instInfo=@strInstCode and a.autoID=b.foreignid;
