CREATE procedure [dbo].[Proc_Check_QY_02XJLLB]
(
	@dtDate varchar(10),
	@strInstCode varchar(20)
)
as
if @dtDate='*****' and @strInstCode='*****'
SELECT  a.dtDate
	  , a.instInfo 
	  , b.autoID
      , b.CHDJS
      , b.CHZWSZFDXJ
      , b.CQDTFYTX
      , b.CWFY
      , b.CZGDZC9819
      , b.CZGDZC9871
      , b.CZHDCS9851
      , b.CZHDXJLCXJ
      , b.CZHDXJLRXJ
      , b.DTFYJS
      , b.DYSKDX
      , b.FPGLLR9845
      , b.GDZCBFSS
      , b.GDZCZJ
      , b.GJGDZC9825
      , b.GMSPJS9803
      , b.HLBDDXJDYX
      , b.JKSSDDXJ
      , b.JLR
      , b.JTDZCJZZB
      , b.JYHDXJLCXJ
      , b.JYHDXJLRXJ
      , b.JYXYSXMDJS
      , b.JYXYSXMDZJ
      , b.QDTZSYSSDDXJ
      , b.QT9897
      , b.QT9915
      , b.RPTCheckType
      , b.RPTFeedbackType
      , b.RPTSendType
      , b.RZZRGDZC
      , b.SDDQTY9799
      , b.SDDQTY9821
      , b.SDDQTY9839
      , b.SDDSFFH
      , b.SHTZSSDDXJ
      , b.TZHDCS9833
      , b.TZHDXJLCXJ
      , b.TZHDXJLRXJ
      , b.TZSS
      , b.TZSZFDXJ
      , b.WXZCTX
      , b.XJDJWDQCYE
      , b.XJDJWDQMYE
      , b.XJDQCYE
      , b.XJDQMYE
      , b.XJJE9813_1
      , b.XJJE9813_2
      , b.XSSPHT9795
      , b.XSTZSSDDXJ
      , b.YNNDQD9893
      , b.YTFYZJ
      , b.ZFDGXSF
      , b.ZFDQTY9809
      , b.ZFDQTY9829
      , b.ZFDQTY9847
      , b.ZFGZGY9805
      , b.ZJE9855_1
      , b.ZJE9885_2
      , b.ZWZWZB
      , b.extend1
      , b.extend2
      , b.extend3
      , b.extend4
      , b.extend5
      , b.FOREIGNID
  FROM QY_JKRCWBB_JC as a, QY_02XJLLB as b
  WHERE a.autoID=b.foreignid;
else
SELECT  a.dtDate
	  , a.instInfo 
	  , b.autoID
      , b.CHDJS
      , b.CHZWSZFDXJ
      , b.CQDTFYTX
      , b.CWFY
      , b.CZGDZC9819
      , b.CZGDZC9871
      , b.CZHDCS9851
      , b.CZHDXJLCXJ
      , b.CZHDXJLRXJ
      , b.DTFYJS
      , b.DYSKDX
      , b.FPGLLR9845
      , b.GDZCBFSS
      , b.GDZCZJ
      , b.GJGDZC9825
      , b.GMSPJS9803
      , b.HLBDDXJDYX
      , b.JKSSDDXJ
      , b.JLR
      , b.JTDZCJZZB
      , b.JYHDXJLCXJ
      , b.JYHDXJLRXJ
      , b.JYXYSXMDJS
      , b.JYXYSXMDZJ
      , b.QDTZSYSSDDXJ
      , b.QT9897
      , b.QT9915
      , b.RPTCheckType
      , b.RPTFeedbackType
      , b.RPTSendType
      , b.RZZRGDZC
      , b.SDDQTY9799
      , b.SDDQTY9821
      , b.SDDQTY9839
      , b.SDDSFFH
      , b.SHTZSSDDXJ
      , b.TZHDCS9833
      , b.TZHDXJLCXJ
      , b.TZHDXJLRXJ
      , b.TZSS
      , b.TZSZFDXJ
      , b.WXZCTX
      , b.XJDJWDQCYE
      , b.XJDJWDQMYE
      , b.XJDQCYE
      , b.XJDQMYE
      , b.XJJE9813_1
      , b.XJJE9813_2
      , b.XSSPHT9795
      , b.XSTZSSDDXJ
      , b.YNNDQD9893
      , b.YTFYZJ
      , b.ZFDGXSF
      , b.ZFDQTY9809
      , b.ZFDQTY9829
      , b.ZFDQTY9847
      , b.ZFGZGY9805
      , b.ZJE9855_1
      , b.ZJE9885_2
      , b.ZWZWZB
      , b.extend1
      , b.extend2
      , b.extend3
      , b.extend4
      , b.extend5
      , b.FOREIGNID
  FROM QY_JKRCWBB_JC as a, QY_02XJLLB as b
  WHERE a.dtDate=@dtDate and a.instInfo=@strInstCode and a.autoID=b.foreignid;
