CREATE procedure [dbo].[Proc_Check_QY_07ZCFZB]
(
	@dtDate varchar(10),
	@strInstCode varchar(20)
)
as
if @dtDate='*****' and @strInstCode='*****'
SELECT  a.dtDate
	  , a.instInfo 
	  , b.autoID
      , b.CH
      , b.CQDTFY
      , b.CQGQTZ
      , b.CQJK
      , b.CQYFK
      , b.CQYSK
      , b.CYZDQTZ
      , b.DQJK
      , b.DYSDSFZ
      , b.DYSDSZC
      , b.FLDFZHJ
      , b.FLDZCHJ
      , b.FZHJ
      , b.FZHSYZQYHJ
      , b.GCWZ
      , b.GDZC
      , b.GDZCQL
      , b.HBZJ
      , b.JKCG
      , b.JYXJRFZ
      , b.JYXJRZC
      , b.KFZC
      , b.KGCSDJRZC
      , b.LDFZHJ
      , b.LDZCHJ
      , b.QTFLDFZ
      , b.QTFLDZC
      , b.QTLDFZ
      , b.QTLDZC
      , b.QTYFK
      , b.QTYSK
      , b.RPTCheckType
      , b.RPTFeedbackType
      , b.RPTSendType
      , b.SCXSWZC
      , b.SSZBHGB
      , b.SY
      , b.SYZQYHJ
      , b.TZXFDC
      , b.WFPLR
      , b.WXZC
      , b.YFGL
      , b.YFLX
      , b.YFPJ
      , b.YFZGXZ
      , b.YFZK_1
      , b.YFZK_2
      , b.YFZQ
      , b.YJFZ
      , b.YJSF
      , b.YNNDQDFLDFZ
      , b.YNNDQDFLDZC
      , b.YQZC
      , b.YSGL
      , b.YSLX
      , b.YSPJ
      , b.YSZK
      , b.YSZK_1
      , b.YYGJ
      , b.ZBGJ
      , b.ZCZJ
      , b.ZJGC
      , b.ZXYFK
      , b.extend1
      , b.extend2
      , b.extend3
      , b.extend4
      , b.extend5
      , b.FOREIGNID
  FROM QY_JKRCWBB_JC as a, QY_07ZCFZB as b
  WHERE a.autoID=b.foreignid;
else
SELECT  a.dtDate
	  , a.instInfo 
	  , b.autoID
      , b.CH
      , b.CQDTFY
      , b.CQGQTZ
      , b.CQJK
      , b.CQYFK
      , b.CQYSK
      , b.CYZDQTZ
      , b.DQJK
      , b.DYSDSFZ
      , b.DYSDSZC
      , b.FLDFZHJ
      , b.FLDZCHJ
      , b.FZHJ
      , b.FZHSYZQYHJ
      , b.GCWZ
      , b.GDZC
      , b.GDZCQL
      , b.HBZJ
      , b.JKCG
      , b.JYXJRFZ
      , b.JYXJRZC
      , b.KFZC
      , b.KGCSDJRZC
      , b.LDFZHJ
      , b.LDZCHJ
      , b.QTFLDFZ
      , b.QTFLDZC
      , b.QTLDFZ
      , b.QTLDZC
      , b.QTYFK
      , b.QTYSK
      , b.RPTCheckType
      , b.RPTFeedbackType
      , b.RPTSendType
      , b.SCXSWZC
      , b.SSZBHGB
      , b.SY
      , b.SYZQYHJ
      , b.TZXFDC
      , b.WFPLR
      , b.WXZC
      , b.YFGL
      , b.YFLX
      , b.YFPJ
      , b.YFZGXZ
      , b.YFZK_1
      , b.YFZK_2
      , b.YFZQ
      , b.YJFZ
      , b.YJSF
      , b.YNNDQDFLDFZ
      , b.YNNDQDFLDZC
      , b.YQZC
      , b.YSGL
      , b.YSLX
      , b.YSPJ
      , b.YSZK
      , b.YSZK_1
      , b.YYGJ
      , b.ZBGJ
      , b.ZCZJ
      , b.ZJGC
      , b.ZXYFK
      , b.extend1
      , b.extend2
      , b.extend3
      , b.extend4
      , b.extend5
      , b.FOREIGNID
  FROM QY_JKRCWBB_JC as a, QY_07ZCFZB as b
  WHERE a.dtDate=@dtDate and a.instInfo=@strInstCode and a.autoID=b.foreignid;
