CREATE procedure [dbo].[Proc_Check_QY_02ZCFZB]
(
	@dtDate varchar(10),
	@strInstCode varchar(20)
)
as
if @dtDate='*****' and @strInstCode='*****'
SELECT  a.dtDate
	  , a.instInfo 
	  , b.autoID
      , b.CH
      , b.CHCCP
      , b.CHYCL
      , b.CQFZHJ
      , b.CQGQTZ
      , b.CQJK
      , b.CQTZ
      , b.CQTZHJ
      , b.CQYFK
      , b.CQZQTZ
      , b.DCLGDZCJSS
      , b.DCLLDZCJSS
      , b.DQJK
      , b.DQTZ
      , b.DTFY
      , b.DYSKDX
      , b.DYSKJX
      , b.DYZC
      , b.DYZCGD9577
      , b.DYZCGDZCXL
      , b.FRZB
      , b.FRZBGJFRZB
      , b.FRZBJTFRZB
      , b.FZHJ
      , b.FZHSYZQYHJ
      , b.GCWZ
      , b.GDZCHJ
      , b.GDZCJE
      , b.GDZCJZ
      , b.GDZCQL
      , b.GDZCYJ
      , b.GDZCZJZZB
      , b.GJZB
      , b.GRZB
      , b.HBJC
      , b.HBZJ
      , b.JTZB
      , b.LDFZHJ
      , b.LDZCHJ
      , b.LJZJ
      , b.QHBZJ
      , b.QTCQFZ
      , b.QTCQFZ9629
      , b.QTCQZC
      , b.QTCQZC9581
      , b.QTLDFZ
      , b.QTLDZC
      , b.QTYFK
      , b.QTYJK
      , b.QTYSK
      , b.RPTCheckType
      , b.RPTFeedbackType
      , b.RPTSendType
      , b.SSGDQY
      , b.SSZB
      , b.SYZQYHJ
      , b.WBBBZSCE
      , b.WFPLR
      , b.WQRDTZSS
      , b.WSZB
      , b.WXJQTZCHJ
      , b.WXZC
      , b.WXZCTDSYQ
      , b.YFFLF
      , b.YFGZ
      , b.YFJJ
      , b.YFLR
      , b.YFPJ
      , b.YFSJ
      , b.YFZK
      , b.YIFZK
      , b.YJFZ
      , b.YNNDQ9533
      , b.YNNDQDCQFZ
      , b.YSBTK
      , b.YSCKTS
      , b.YSGL
      , b.YSLX
      , b.YSPJ
      , b.YSZK
      , b.YTFY
      , b.YUSZK
      , b.YYGJ
      , b.YYGJBCLDZB
      , b.YYGJFDYYGJ
      , b.YYGJGJJ
      , b.ZBGJ
      , b.ZCZJ
      , b.ZJGC
      , b.ZXYFK
      , b.extend1
      , b.extend2
      , b.extend3
      , b.extend4
      , b.extend5
      , b.FOREIGNID
  FROM QY_JKRCWBB_JC as a, QY_02ZCFZB as b
  WHERE a.autoID=b.foreignid;
else
SELECT  a.dtDate
	  , a.instInfo 
	  , b.autoID
      , b.CH
      , b.CHCCP
      , b.CHYCL
      , b.CQFZHJ
      , b.CQGQTZ
      , b.CQJK
      , b.CQTZ
      , b.CQTZHJ
      , b.CQYFK
      , b.CQZQTZ
      , b.DCLGDZCJSS
      , b.DCLLDZCJSS
      , b.DQJK
      , b.DQTZ
      , b.DTFY
      , b.DYSKDX
      , b.DYSKJX
      , b.DYZC
      , b.DYZCGD9577
      , b.DYZCGDZCXL
      , b.FRZB
      , b.FRZBGJFRZB
      , b.FRZBJTFRZB
      , b.FZHJ
      , b.FZHSYZQYHJ
      , b.GCWZ
      , b.GDZCHJ
      , b.GDZCJE
      , b.GDZCJZ
      , b.GDZCQL
      , b.GDZCYJ
      , b.GDZCZJZZB
      , b.GJZB
      , b.GRZB
      , b.HBJC
      , b.HBZJ
      , b.JTZB
      , b.LDFZHJ
      , b.LDZCHJ
      , b.LJZJ
      , b.QHBZJ
      , b.QTCQFZ
      , b.QTCQFZ9629
      , b.QTCQZC
      , b.QTCQZC9581
      , b.QTLDFZ
      , b.QTLDZC
      , b.QTYFK
      , b.QTYJK
      , b.QTYSK
      , b.RPTCheckType
      , b.RPTFeedbackType
      , b.RPTSendType
      , b.SSGDQY
      , b.SSZB
      , b.SYZQYHJ
      , b.WBBBZSCE
      , b.WFPLR
      , b.WQRDTZSS
      , b.WSZB
      , b.WXJQTZCHJ
      , b.WXZC
      , b.WXZCTDSYQ
      , b.YFFLF
      , b.YFGZ
      , b.YFJJ
      , b.YFLR
      , b.YFPJ
      , b.YFSJ
      , b.YFZK
      , b.YIFZK
      , b.YJFZ
      , b.YNNDQ9533
      , b.YNNDQDCQFZ
      , b.YSBTK
      , b.YSCKTS
      , b.YSGL
      , b.YSLX
      , b.YSPJ
      , b.YSZK
      , b.YTFY
      , b.YUSZK
      , b.YYGJ
      , b.YYGJBCLDZB
      , b.YYGJFDYYGJ
      , b.YYGJGJJ
      , b.ZBGJ
      , b.ZCZJ
      , b.ZJGC
      , b.ZXYFK
      , b.extend1
      , b.extend2
      , b.extend3
      , b.extend4
      , b.extend5
      , b.FOREIGNID
  FROM QY_JKRCWBB_JC as a, QY_02ZCFZB as b
  WHERE a.dtDate=@dtDate and a.instInfo=@strInstCode and a.autoID=b.foreignid;
