CREATE procedure [dbo].[Proc_Check_QY_07XJLLB]
(
	@dtDate varchar(10),
	@strInstCode varchar(20)
)
as
if @dtDate='*****' and @strInstCode='*****'
SELECT  a.dtDate
	  , a.instInfo 
      , b.autoID
      , b.CHZWSZFDXJ
      , b.CQDTFYTX
      , b.CWFY_1
      , b.CZGDZCWXZCHQTCQZCDSS
      , b.CZGDZCWXZCHQTCQZCSSHDXJJE
      , b.CZHDCSDXJLLJE
      , b.CZHDXJLRXJ
      , b.CZHDXJLRXJ_1
      , b.CZZGSJQTYYDWSDDXJJE
      , b.DTFYJS
      , b.DYSDSFZZJ
      , b.DYSDSZCJS
      , b.FPGLLRHCFLXSZFDXJ
      , b.GDZCBFSS
      , b.GDZCZJYQZCZHSCXSWZCZJ
      , b.GMGDZCWXZCHQTCQZCSZFDXJ
      , b.GMSPJSLWZFDXJ
      , b.GYJZBDSS
      , b.JLR_1
      , b.JYHDCSDXJLLJE
      , b.JYHDCSDXJLLJE_1
      , b.JYHDXJLCXJ
      , b.JYHDXJLRXJ
      , b.JYXYFXMDZJ
      , b.JYXYSXMDJS
      , b.QCXJJXJDJWYE
      , b.QDJKSDDXJ
      , b.QDTZSYSSDDXJ
      , b.QDZGSJQTSYDWZFDXJJE
      , b.QMXJJXJDJWYEL
      , b.QT
      , b.QT_1
      , b.RPTCheckType
      , b.RPTFeedbackType
      , b.RPTSendType
      , b.RZZRGDZC
      , b.SDDSFFH
      , b.SDQTYCZHDYGDXJ
      , b.SDQTYJYHDYGDXJ
      , b.SDQTYTZHDYGDXJ
      , b.SHTZSSDDXJ
      , b.SLBDDXJJXJDJWDYX
      , b.TZHDCSDXJLLJE
      , b.TZHDXJLRXJ
      , b.TZHDXJLRXJ_1
      , b.TZSS
      , b.TZSZFDXJ
      , b.WXZCTX
      , b.XJDJWDQCYE
      , b.XJDJWDQMYE
      , b.XJDQCYE
      , b.XJDQMYE
      , b.XJJXJDJWJZEW
      , b.XJJXJDJWJZZJE
      , b.XSCPHTGLWSDDXJ
      , b.XSTZSDDXJ
      , b.YNNDQDKZHGSZQ
      , b.YTFYZJ
      , b.ZCJZZB
      , b.ZFDGXSF
      , b.ZFGZGYJWZGZFDXJ
      , b.ZFQTYCZHDYGDXJ
      , b.ZFQTYJYHDYGDXJ
      , b.ZFQTYTZHDYGDXJ
      , b.ZHDJS
      , b.ZWZWZB
      , b.extend1
      , b.extend2
      , b.extend3
      , b.extend4
      , b.extend5
      , b.FOREIGNID    
  FROM QY_JKRCWBB_JC as a, QY_07XJLLB as b
  WHERE a.autoID=b.foreignid;
else
SELECT  a.dtDate
	  , a.instInfo 
      , b.autoID
      , b.CHZWSZFDXJ
      , b.CQDTFYTX
      , b.CWFY_1
      , b.CZGDZCWXZCHQTCQZCDSS
      , b.CZGDZCWXZCHQTCQZCSSHDXJJE
      , b.CZHDCSDXJLLJE
      , b.CZHDXJLRXJ
      , b.CZHDXJLRXJ_1
      , b.CZZGSJQTYYDWSDDXJJE
      , b.DTFYJS
      , b.DYSDSFZZJ
      , b.DYSDSZCJS
      , b.FPGLLRHCFLXSZFDXJ
      , b.GDZCBFSS
      , b.GDZCZJYQZCZHSCXSWZCZJ
      , b.GMGDZCWXZCHQTCQZCSZFDXJ
      , b.GMSPJSLWZFDXJ
      , b.GYJZBDSS
      , b.JLR_1
      , b.JYHDCSDXJLLJE
      , b.JYHDCSDXJLLJE_1
      , b.JYHDXJLCXJ
      , b.JYHDXJLRXJ
      , b.JYXYFXMDZJ
      , b.JYXYSXMDJS
      , b.QCXJJXJDJWYE
      , b.QDJKSDDXJ
      , b.QDTZSYSSDDXJ
      , b.QDZGSJQTSYDWZFDXJJE
      , b.QMXJJXJDJWYEL
      , b.QT
      , b.QT_1
      , b.RPTCheckType
      , b.RPTFeedbackType
      , b.RPTSendType
      , b.RZZRGDZC
      , b.SDDSFFH
      , b.SDQTYCZHDYGDXJ
      , b.SDQTYJYHDYGDXJ
      , b.SDQTYTZHDYGDXJ
      , b.SHTZSSDDXJ
      , b.SLBDDXJJXJDJWDYX
      , b.TZHDCSDXJLLJE
      , b.TZHDXJLRXJ
      , b.TZHDXJLRXJ_1
      , b.TZSS
      , b.TZSZFDXJ
      , b.WXZCTX
      , b.XJDJWDQCYE
      , b.XJDJWDQMYE
      , b.XJDQCYE
      , b.XJDQMYE
      , b.XJJXJDJWJZEW
      , b.XJJXJDJWJZZJE
      , b.XSCPHTGLWSDDXJ
      , b.XSTZSDDXJ
      , b.YNNDQDKZHGSZQ
      , b.YTFYZJ
      , b.ZCJZZB
      , b.ZFDGXSF
      , b.ZFGZGYJWZGZFDXJ
      , b.ZFQTYCZHDYGDXJ
      , b.ZFQTYJYHDYGDXJ
      , b.ZFQTYTZHDYGDXJ
      , b.ZHDJS
      , b.ZWZWZB
      , b.extend1
      , b.extend2
      , b.extend3
      , b.extend4
      , b.extend5
      , b.FOREIGNID    
  FROM QY_JKRCWBB_JC as a, QY_07XJLLB as b
  WHERE a.dtDate=@dtDate and a.instInfo=@strInstCode and a.autoID=b.foreignid;
