CREATE PROCEDURE PROC_CREDIT_COUNT
(
	IN p_INSTINFO VARCHAR(50),
	IN p_TABLENAME VARCHAR(128),
	IN FIRSTRESULT VARCHAR(10),
	IN PAGECOUNT VARCHAR(10)
)
  DYNAMIC RESULT SETS 1
  LANGUAGE SQL
BEGIN
DECLARE CC VARCHAR(4000);
DECLARE V_CURSQL VARCHAR(4000); 

DECLARE cur CURSOR WITH RETURN TO CALLER FOR CC;

IF p_TABLENAME = 'QY_DKYW_JC'
	THEN
	SET V_CURSQL = 'SELECT * FROM 

	(SELECT COUNT(1) AS HTBS FROM QY_HTXX WHERE EXISTS (
	SELECT * FROM (SELECT FOREIGNID,MAX(QY_HTXX.EXTEND2) AS EXTEND2 FROM QY_HTXX,QY_DKYW_JC WHERE QY_HTXX.FOREIGNID = QY_DKYW_JC.AUTOID AND INSTINFO = '||p_INSTINFO||' AND QY_DKYW_JC.XXJLCZLX = ''1'' AND QY_HTXX.RPTFEEDBACKTYPE = ''2'' GROUP BY FOREIGNID) TEMP 
	WHERE QY_HTXX.FOREIGNID = TEMP.FOREIGNID AND QY_HTXX.EXTEND2 = TEMP.EXTEND2 AND QY_HTXX.HTYXZT = ''1'')) A
	CROSS JOIN

	(SELECT COUNT(1) AS BS,SUM(CAST(DKJJJE AS DECIMAL(17,2))) AS JE,SUM(CAST(DKJJYE AS DECIMAL(17,2))) AS YE FROM QY_JJXX WHERE EXISTS (
	SELECT * FROM (SELECT FOREIGNID,JJBH,MAX(QY_JJXX.EXTEND2) AS EXTEND2 FROM QY_JJXX,QY_DKYW_JC WHERE QY_JJXX.FOREIGNID = QY_DKYW_JC.AUTOID AND INSTINFO = '||p_INSTINFO||' AND QY_DKYW_JC.XXJLCZLX = ''1'' AND QY_JJXX.RPTFEEDBACKTYPE = ''2'' GROUP BY FOREIGNID,JJBH) TEMP 
	WHERE QY_JJXX.FOREIGNID = TEMP.FOREIGNID AND QY_JJXX.JJBH = TEMP.JJBH AND QY_JJXX.EXTEND2 = TEMP.EXTEND2 AND QY_JJXX.DKJJYE <> ''0.00'')) B';
	END IF;

IF p_TABLENAME = 'QY_BLYW_JC'
	THEN
	SET V_CURSQL = 'SELECT COUNT(1) AS BS,SUM(CAST(XZJE AS DECIMAL(17,2))) AS JE,SUM(CAST(XZYE AS DECIMAL(17,2))) AS YE FROM QY_BLXZXX WHERE EXISTS (
	SELECT * FROM (SELECT FOREIGNID,MAX(QY_BLXZXX.EXTEND2) AS EXTEND2 FROM QY_BLXZXX,QY_BLYW_JC WHERE QY_BLXZXX.FOREIGNID = QY_BLYW_JC.AUTOID AND INSTINFO = '||p_INSTINFO||' AND QY_BLYW_JC.XXJLCZLX = ''1'' AND QY_BLXZXX.RPTFEEDBACKTYPE = ''2'' GROUP BY FOREIGNID) TEMP 
	WHERE QY_BLXZXX.FOREIGNID = TEMP.FOREIGNID AND QY_BLXZXX.EXTEND2 = TEMP.EXTEND2 AND QY_BLXZXX.XZYE <> ''0.00'')';
	END IF;

IF p_TABLENAME = 'QY_PJTX_JC'
	THEN
	SET V_CURSQL = 'SELECT COUNT(1) AS BS,SUM(CAST(TXJE AS DECIMAL(17,2))) AS JE,SUM(CAST(TXJE AS DECIMAL(17,2))) AS YE FROM QY_TXYWXX WHERE EXISTS (
	SELECT * FROM (SELECT FOREIGNID,MAX(QY_TXYWXX.EXTEND2) AS EXTEND2 FROM QY_TXYWXX,QY_PJTX_JC WHERE QY_TXYWXX.FOREIGNID = QY_PJTX_JC.AUTOID AND INSTINFO = '||p_INSTINFO||' AND QY_PJTX_JC.XXJLCZLX = ''1'' AND QY_TXYWXX.RPTFEEDBACKTYPE = ''2'' GROUP BY FOREIGNID) TEMP 
	WHERE QY_TXYWXX.FOREIGNID = TEMP.FOREIGNID AND QY_TXYWXX.EXTEND2 = TEMP.EXTEND2 AND QY_TXYWXX.PJZT = ''1'')';
	END IF;
	
IF p_TABLENAME = 'QY_MYRZ_JC'
	THEN
	SET V_CURSQL = 'SELECT * FROM 

	(SELECT COUNT(1) AS HTBS FROM QY_RZXYXX WHERE EXISTS (
	SELECT * FROM (SELECT FOREIGNID,MAX(QY_RZXYXX.EXTEND2) AS EXTEND2 FROM QY_RZXYXX,QY_MYRZ_JC WHERE QY_RZXYXX.FOREIGNID = QY_MYRZ_JC.AUTOID AND INSTINFO = '||p_INSTINFO||' AND QY_MYRZ_JC.XXJLCZLX = ''1'' AND QY_RZXYXX.RPTFEEDBACKTYPE = ''2'' GROUP BY FOREIGNID) TEMP 
	WHERE QY_RZXYXX.FOREIGNID = TEMP.FOREIGNID AND QY_RZXYXX.EXTEND2 = TEMP.EXTEND2 AND QY_RZXYXX.XYYXZT = ''1'')) A
	CROSS JOIN

	(SELECT COUNT(1) AS BS,SUM(CAST(RZJE AS DECIMAL(17,2))) AS JE,SUM(CAST(RZYE AS DECIMAL(17,2))) AS YE FROM QY_RZYWXX WHERE EXISTS (
	SELECT * FROM (SELECT FOREIGNID,RZYWBH,MAX(QY_RZYWXX.EXTEND2) AS EXTEND2 FROM QY_RZYWXX,QY_MYRZ_JC WHERE QY_RZYWXX.FOREIGNID = QY_MYRZ_JC.AUTOID AND INSTINFO = '||p_INSTINFO||' AND QY_MYRZ_JC.XXJLCZLX = ''1'' AND QY_RZYWXX.RPTFEEDBACKTYPE = ''2'' GROUP BY FOREIGNID,RZYWBH) TEMP 
	WHERE QY_RZYWXX.FOREIGNID = TEMP.FOREIGNID AND QY_RZYWXX.RZYWBH = TEMP.RZYWBH AND QY_RZYWXX.EXTEND2 = TEMP.EXTEND2 AND QY_RZYWXX.RZYE <> ''0.00'')) B';
	END IF;

IF p_TABLENAME = 'QY_XYZYW_JC'
	THEN
	SET V_CURSQL = 'SELECT COUNT(1) AS BS,SUM(CAST(KZJE AS DECIMAL(17,2))) AS JE,SUM(CAST(XYZYE AS DECIMAL(17,2))) AS YE FROM QY_XYZYWXX WHERE EXISTS (
	SELECT * FROM (SELECT FOREIGNID,MAX(QY_XYZYWXX.EXTEND2) AS EXTEND2 FROM QY_XYZYWXX,QY_XYZYW_JC WHERE QY_XYZYWXX.FOREIGNID = QY_XYZYW_JC.AUTOID AND INSTINFO = '||p_INSTINFO||' AND QY_XYZYW_JC.XXJLCZLX = ''1'' AND QY_XYZYWXX.RPTFEEDBACKTYPE = ''2'' GROUP BY FOREIGNID) TEMP 
	WHERE QY_XYZYWXX.FOREIGNID = TEMP.FOREIGNID AND QY_XYZYWXX.EXTEND2 = TEMP.EXTEND2 AND QY_XYZYWXX.XYZZT = ''1'')';
	END IF;
	
IF p_TABLENAME = 'QY_BHYW_JC'
	THEN
	SET V_CURSQL = 'SELECT COUNT(1) AS BS,SUM(CAST(BHJE AS DECIMAL(17,2))) AS JE,SUM(CAST(BHYE AS DECIMAL(17,2))) AS YE FROM QY_BHYWXX WHERE EXISTS (
	SELECT * FROM (SELECT FOREIGNID,MAX(QY_BHYWXX.EXTEND2) AS EXTEND2 FROM QY_BHYWXX,QY_BHYW_JC WHERE QY_BHYWXX.FOREIGNID = QY_BHYW_JC.AUTOID AND INSTINFO = '||p_INSTINFO||' AND QY_BHYW_JC.XXJLCZLX = ''1'' AND QY_BHYWXX.RPTFEEDBACKTYPE = ''2'' GROUP BY FOREIGNID) TEMP 
	WHERE QY_BHYWXX.FOREIGNID = TEMP.FOREIGNID AND QY_BHYWXX.EXTEND2 = TEMP.EXTEND2 AND QY_BHYWXX.BHZT = ''1'')';
	END IF;

IF p_TABLENAME = 'QY_YHCDHP_JC'
	THEN
	SET V_CURSQL = 'SELECT COUNT(1) AS BS,SUM(CAST(HPJE AS DECIMAL(17,2))) AS JE,SUM(CAST(HPJE AS DECIMAL(17,2))) AS YE FROM QY_HPYWXX WHERE EXISTS (
	SELECT * FROM (SELECT FOREIGNID,MAX(QY_HPYWXX.EXTEND2) AS EXTEND2 FROM QY_HPYWXX,QY_YHCDHP_JC WHERE QY_HPYWXX.FOREIGNID = QY_YHCDHP_JC.AUTOID AND INSTINFO = '||p_INSTINFO||' AND QY_YHCDHP_JC.XXJLCZLX = ''1'' AND QY_HPYWXX.RPTFEEDBACKTYPE = ''2'' GROUP BY FOREIGNID) TEMP 
	WHERE QY_HPYWXX.FOREIGNID = TEMP.FOREIGNID AND QY_HPYWXX.EXTEND2 = TEMP.EXTEND2 AND QY_HPYWXX.HPZT = ''1'')';
	END IF;

IF p_TABLENAME = 'QY_GKSX_JC'
	THEN
	SET V_CURSQL = 'SELECT COUNT(1) AS BS,SUM(CAST(SXED AS DECIMAL(17,2))) AS JE FROM QY_SXYWXX WHERE EXISTS (
	SELECT * FROM (SELECT FOREIGNID,MAX(QY_SXYWXX.EXTEND2) AS EXTEND2 FROM QY_SXYWXX,QY_GKSX_JC WHERE QY_SXYWXX.FOREIGNID = QY_GKSX_JC.AUTOID AND INSTINFO = '||p_INSTINFO||' AND QY_GKSX_JC.XXJLCZLX = ''1'' AND QY_SXYWXX.RPTFEEDBACKTYPE = ''2'' GROUP BY FOREIGNID) TEMP 
	WHERE QY_SXYWXX.FOREIGNID = TEMP.FOREIGNID AND QY_SXYWXX.EXTEND2 = TEMP.EXTEND2 AND QY_SXYWXX.SXEDZXSXRQ <> QY_SXYWXX.extend2)';
	END IF;

IF p_TABLENAME = 'QY_DBXX_JC'
	THEN
	SET V_CURSQL = 'SELECT * FROM (
	SELECT COUNT(1) AS BZBS,SUM(CAST(BZJE AS DECIMAL(17,2))) AS BZJE FROM (
	SELECT BZRDDKKBM,BZHTBH,MAX(BZJE) AS BZJE FROM QY_DBHTXX WHERE EXISTS (
	SELECT * FROM (SELECT BZRDDKKBM,BZHTBH,MAX(QY_DBHTXX.EXTEND2) AS EXTEND2 FROM QY_DBHTXX,QY_DBXX_JC WHERE QY_DBHTXX.FOREIGNID = QY_DBXX_JC.AUTOID AND INSTINFO = '||p_INSTINFO||' AND QY_DBXX_JC.XXJLCZLX = ''1'' AND QY_DBHTXX.RPTFEEDBACKTYPE = ''2'' AND QY_DBHTXX.HTYXZT = ''1'' GROUP BY BZRDDKKBM,BZHTBH) TEMP
	WHERE QY_DBHTXX.BZRDDKKBM = TEMP.BZRDDKKBM AND QY_DBHTXX.BZHTBH = TEMP.BZHTBH AND QY_DBHTXX.EXTEND2 = TEMP.EXTEND2) GROUP BY BZRDDKKBM,BZHTBH) TEMP2) A
	CROSS JOIN

	(SELECT COUNT(1) AS ZRRBZBS,SUM(CAST(BZJE AS DECIMAL(17,2))) AS ZRRBZJE FROM (
	SELECT ZJLX,ZJHM,MAX(BZJE) AS BZJE FROM QY_ZRRBZHTXX WHERE EXISTS (
	SELECT * FROM (SELECT ZJLX,ZJHM,BZHTBH,MAX(QY_ZRRBZHTXX.EXTEND2) AS EXTEND2 FROM QY_ZRRBZHTXX,QY_DBXX_JC WHERE QY_ZRRBZHTXX.FOREIGNID = QY_DBXX_JC.AUTOID AND INSTINFO = '||p_INSTINFO||' AND QY_DBXX_JC.XXJLCZLX = ''1'' AND QY_ZRRBZHTXX.RPTFEEDBACKTYPE = ''2'' AND QY_ZRRBZHTXX.HTYXZT = ''1'' GROUP BY ZJLX,ZJHM,BZHTBH) TEMP
	WHERE QY_ZRRBZHTXX.ZJLX = TEMP.ZJLX AND QY_ZRRBZHTXX.ZJHM = TEMP.ZJHM AND QY_ZRRBZHTXX.BZHTBH = TEMP.BZHTBH AND QY_ZRRBZHTXX.EXTEND2 = TEMP.EXTEND2) GROUP BY ZJLX,ZJHM,BZHTBH) TEMP2) B
	CROSS JOIN

	(SELECT COUNT(1) AS DYBS,SUM(CAST(DYJE AS DECIMAL(17,2))) AS DYJE FROM (
	SELECT DYRDKKBM,DYHTBM,SUM(CAST(DYJE AS DECIMAL(17,2))) AS DYJE FROM (
	SELECT DYRDKKBM,DYHTBM,DYXH,MAX(DYJE) AS DYJE FROM QY_DYHTXX WHERE EXISTS (
	SELECT * FROM (SELECT DYRDKKBM,DYHTBM,DYXH,MAX(QY_DYHTXX.EXTEND2) AS EXTEND2 FROM QY_DYHTXX,QY_DBXX_JC WHERE QY_DYHTXX.FOREIGNID = QY_DBXX_JC.AUTOID AND INSTINFO = '||p_INSTINFO||' AND QY_DBXX_JC.XXJLCZLX = ''1'' AND QY_DYHTXX.RPTFEEDBACKTYPE = ''2'' AND QY_DYHTXX.HTYXZT = ''1'' GROUP BY DYRDKKBM,DYHTBM,DYXH) TEMP
	WHERE QY_DYHTXX.DYRDKKBM = TEMP.DYRDKKBM AND QY_DYHTXX.DYHTBM = TEMP.DYHTBM AND QY_DYHTXX.DYXH = TEMP.DYXH AND QY_DYHTXX.EXTEND2 = TEMP.EXTEND2) GROUP BY DYRDKKBM,DYHTBM,DYXH) TEMP2 
	GROUP BY DYRDKKBM,DYHTBM) TEMP3) C
	CROSS JOIN

	(SELECT COUNT(1) AS ZRRDYBS,SUM(CAST(DYJE AS DECIMAL(17,2))) AS ZRRDYJE FROM (
	SELECT ZJLX,ZJHM,DYHTBH,SUM(CAST(DYJE AS DECIMAL(17,2))) AS DYJE FROM (
	SELECT ZJLX,ZJHM,DYHTBH,MAX(DYJE) AS DYJE FROM QY_ZRRDYHTXX WHERE EXISTS (
	SELECT * FROM (SELECT ZJLX,ZJHM,DYHTBH,DYXH,MAX(QY_ZRRDYHTXX.EXTEND2) AS EXTEND2 FROM QY_ZRRDYHTXX,QY_DBXX_JC WHERE QY_ZRRDYHTXX.FOREIGNID = QY_DBXX_JC.AUTOID AND INSTINFO = '||p_INSTINFO||' AND QY_DBXX_JC.XXJLCZLX = ''1'' AND QY_ZRRDYHTXX.RPTFEEDBACKTYPE = ''2'' AND QY_ZRRDYHTXX.HTYXZT = ''1'' GROUP BY ZJLX,ZJHM,DYHTBH,DYXH) TEMP
	WHERE QY_ZRRDYHTXX.ZJLX = TEMP.ZJLX AND QY_ZRRDYHTXX.ZJHM = TEMP.ZJHM AND QY_ZRRDYHTXX.DYHTBH = TEMP.DYHTBH AND QY_ZRRDYHTXX.DYXH = TEMP.DYXH AND QY_ZRRDYHTXX.EXTEND2 = TEMP.EXTEND2) GROUP BY ZJLX,ZJHM,DYHTBH,DYXH) TEMP2
	GROUP BY ZJLX,ZJHM,DYHTBH) TEMP3) D
	CROSS JOIN

	(SELECT COUNT(1) AS ZYBS,SUM(CAST(ZYJE AS DECIMAL(17,2))) AS ZYJE FROM (
	SELECT CZRDDKKBM,ZYHTBH,SUM(CAST(ZYJE AS DECIMAL(17,2))) AS ZYJE FROM (
	SELECT CZRDDKKBM,ZYHTBH,ZYXH,MAX(ZYJE) AS ZYJE FROM QY_ZYHTXX WHERE EXISTS (
	SELECT * FROM (SELECT CZRDDKKBM,ZYHTBH,ZYXH,MAX(QY_ZYHTXX.EXTEND2) AS EXTEND2 FROM QY_ZYHTXX,QY_DBXX_JC WHERE QY_ZYHTXX.FOREIGNID = QY_DBXX_JC.AUTOID AND INSTINFO = '||p_INSTINFO||' AND QY_DBXX_JC.XXJLCZLX = ''1'' AND QY_ZYHTXX.RPTFEEDBACKTYPE = ''2'' AND QY_ZYHTXX.HTYXZT = ''1'' GROUP BY CZRDDKKBM,ZYHTBH,ZYXH) TEMP
	WHERE QY_ZYHTXX.CZRDDKKBM = TEMP.CZRDDKKBM AND QY_ZYHTXX.ZYHTBH = TEMP.ZYHTBH AND QY_ZYHTXX.ZYXH = TEMP.ZYXH AND QY_ZYHTXX.EXTEND2 = TEMP.EXTEND2) GROUP BY CZRDDKKBM,ZYHTBH,ZYXH) TEMP2
	GROUP BY CZRDDKKBM,ZYHTBH) TEMP3) E
	CROSS JOIN

	(SELECT COUNT(1) AS ZRRZYBS,SUM(CAST(ZYJE AS DECIMAL(17,2))) AS ZRRZYJE FROM (
	SELECT ZJLX,ZJHM,ZYHTBH,SUM(CAST(ZYJE AS DECIMAL(17,2))) AS ZYJE FROM (
	SELECT ZJLX,ZJHM,ZYHTBH,MAX(ZYJE) AS ZYJE FROM QY_ZRRZYHTXX WHERE EXISTS (
	SELECT * FROM (SELECT ZJLX,ZJHM,ZYHTBH,ZYXH,MAX(QY_ZRRZYHTXX.EXTEND2) AS EXTEND2 FROM QY_ZRRZYHTXX,QY_DBXX_JC WHERE QY_ZRRZYHTXX.FOREIGNID = QY_DBXX_JC.AUTOID AND INSTINFO = '||p_INSTINFO||' AND QY_DBXX_JC.XXJLCZLX = ''1'' AND QY_ZRRZYHTXX.RPTFEEDBACKTYPE = ''2'' AND QY_ZRRZYHTXX.HTYXZT = ''1'' GROUP BY ZJLX,ZJHM,ZYHTBH,ZYXH) TEMP
	WHERE QY_ZRRZYHTXX.ZJLX = TEMP.ZJLX AND QY_ZRRZYHTXX.ZJHM = TEMP.ZJHM AND QY_ZRRZYHTXX.ZYHTBH = TEMP.ZYHTBH AND QY_ZRRZYHTXX.ZYXH = TEMP.ZYXH AND QY_ZRRZYHTXX.EXTEND2 = TEMP.EXTEND2) GROUP BY ZJLX,ZJHM,ZYHTBH,ZYXH) TEMP2
	GROUP BY ZJLX,ZJHM,ZYHTBH) TEMP3) F';
	END IF;

IF p_TABLENAME = 'QY_DKXX_JC'
	THEN
	SET V_CURSQL = 'SELECT COUNT(1) AS BS,SUM(CAST(DKJE AS DECIMAL(17,2))) AS JE,SUM(CAST(DKYE AS DECIMAL(17,2))) AS YE FROM QY_DKYWXX WHERE EXISTS (
	SELECT * FROM (SELECT FOREIGNID,MAX(QY_DKYWXX.EXTEND2) AS EXTEND2 FROM QY_DKYWXX,QY_DKXX_JC WHERE QY_DKYWXX.FOREIGNID = QY_DKXX_JC.AUTOID AND INSTINFO = '||p_INSTINFO||' AND QY_DKXX_JC.XXJLCZLX = ''1'' AND QY_DKYWXX.RPTFEEDBACKTYPE = ''2'' GROUP BY FOREIGNID) TEMP 
	WHERE QY_DKYWXX.FOREIGNID = TEMP.FOREIGNID AND QY_DKYWXX.EXTEND2 = TEMP.EXTEND2 AND QY_DKYWXX.DKYE <> ''0.00'')';
	END IF;

IF p_TABLENAME = 'QY_QXXX_JC'
	THEN
	SET V_CURSQL = 'SELECT * FROM 

	(SELECT SUM(CAST(QXYE AS DECIMAL(17,2))) AS BN FROM QY_QXYWXX WHERE EXISTS (
	SELECT * FROM (SELECT FOREIGNID,MAX(QY_QXYWXX.EXTEND2) AS EXTEND2 FROM QY_QXYWXX,QY_QXXX_JC WHERE QY_QXYWXX.FOREIGNID = QY_QXXX_JC.AUTOID AND INSTINFO = '||p_INSTINFO||' AND QY_QXXX_JC.XXJLCZLX = ''1'' AND QY_QXYWXX.RPTFEEDBACKTYPE = ''2'' GROUP BY FOREIGNID) TEMP 
	WHERE QY_QXYWXX.FOREIGNID = TEMP.FOREIGNID AND QY_QXYWXX.EXTEND2 = TEMP.EXTEND2 AND QY_QXYWXX.QXYE <> ''0.00'' AND QY_QXYWXX.QXLX = ''1'')) A 
	CROSS JOIN 
	
	(SELECT SUM(CAST(QXYE AS DECIMAL(17,2))) AS BW FROM QY_QXYWXX WHERE EXISTS (
	SELECT * FROM (SELECT FOREIGNID,MAX(QY_QXYWXX.EXTEND2) AS EXTEND2 FROM QY_QXYWXX,QY_QXXX_JC WHERE QY_QXYWXX.FOREIGNID = QY_QXXX_JC.AUTOID AND INSTINFO = '||p_INSTINFO||' AND QY_QXXX_JC.XXJLCZLX = ''1'' AND QY_QXYWXX.RPTFEEDBACKTYPE = ''2'' GROUP BY FOREIGNID) TEMP 
	WHERE QY_QXYWXX.FOREIGNID = TEMP.FOREIGNID AND QY_QXYWXX.EXTEND2 = TEMP.EXTEND2 AND QY_QXYWXX.QXYE <> ''0.00'' AND QY_QXYWXX.QXLX = ''2'')) B';
	END IF;
	
PREPARE CC FROM V_CURSQL;

OPEN cur;
END